// ===========================================================================
//  pyths-safe.js — the ONE safe API the PythScribe build plugins must use for
//  (a) selecting the compiler executable and (b) touching the filesystem.
//
//  SHARED SOURCE — this file is duplicated BYTE-FOR-BYTE into every plugin
//  package (`packages/vite-plugin-pyths/`, `packages/next-plugin-pyths/`)
//  because each package is published to npm standalone and cannot import from
//  a sibling. `test-safe-parity.mjs` in each package fails if the copies drift.
//  Edit one, copy to the other, run both test files.
//
//  ---------------------------------------------------------------------------
//  Why this file exists (security scan 2026-08-12, findings #1 / #2 / #6)
//
//  The CLI (`crates/pyths_cli`) was hardened during the OWASP campaign: it
//  resolves programs through `procutil.rs::resolve_program` (PATH only, never
//  the cwd) and writes generated files through
//  `compile.rs::write_generated_sibling` (no-follow + ownership-aware). The
//  build plugins re-implemented both with plain `execFileSync("pyths", …)` and
//  `writeFileSync`/`unlinkSync`, so the same defect classes survived on the
//  plugin side. This module ports those two controls to JavaScript.
//
//    #1 CWE-426 untrusted search path — a bare program name is resolved by the
//       OS/libuv at spawn time. A `.` element in PATH (very common on Windows)
//       makes that search include the CURRENT DIRECTORY, so a hostile repo
//       shipping `./pyths.exe` gets code execution the moment a developer runs
//       `vite build`. Reproduced on Node 22 / win32; see
//       `test-resolve-bin.mjs::"a . entry in PATH must not select a
//       cwd-planted executable"`.
//
//    #2 CWE-59 symlink follow — `writeFileSync(declPath, …)` follows a
//       final-component symlink, so a checked-in `Foo.d.ps.ts -> ~/.bashrc`
//       has the plugin write generated content into the link target.
//
//    #6 CWE-73 unowned deletion — the old `finally` block unlinked
//       `<stem>.js` / `.js.map` / `.d.ts` beside the SOURCE whenever they
//       existed, deleting hand-written project files the CLI itself refuses to
//       overwrite. Fixed by compiling into a private per-invocation directory
//       (`makePrivateTempDir`) so nothing adjacent to the source is ever
//       created or removed.
// ===========================================================================

import { execFileSync } from "node:child_process";
import {
    closeSync,
    constants as FS,
    existsSync,
    fstatSync,
    ftruncateSync,
    lstatSync,
    mkdirSync,
    openSync,
    readFileSync,
    readSync,
    rmSync,
    statSync,
    writeFileSync,
    writeSync,
} from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { delimiter, dirname, isAbsolute, join, resolve } from "node:path";

// ---------------------------------------------------------------------------
// Generated-file marker (mirrors compile.rs::GENERATED_MARKER)
// ---------------------------------------------------------------------------

/** Marker the CLI stamps at the top of every generated `.js` / `.d.ts`. */
export const GENERATED_MARKER = "@generated by PythScribe";

/**
 * True iff `text` is PythScribe-generated output. P4: the marker must be the
 * LEADING `//` comment, not a substring anywhere in the first 512 bytes — a
 * hand-written file that merely mentions "@generated by PythScribe" (e.g. in
 * documentation) must NOT be treated as owned and overwritten. Mirrors
 * `compile.rs::looks_pyths_generated`.
 */
export function looksPythsGenerated(text) {
    return text.trimStart().startsWith("// " + GENERATED_MARKER);
}

// ---------------------------------------------------------------------------
// #2 — no-follow, ownership-aware sibling writer
// ---------------------------------------------------------------------------

/**
 * Write a compiler-generated sibling safely. JS port of
 * `crates/pyths_cli/src/commands/compile.rs::write_generated_sibling`.
 *
 * Refuses to:
 *   1. write through a **symlink** (or any non-regular file) — the write would
 *      land on the link's target instead of creating a sibling;
 *   2. clobber an existing regular file that does **not** carry the generated
 *      marker, i.e. one PythScribe did not produce (when `markerAware`).
 *
 * Residual TOCTOU between the `lstat` and the write matches the Rust writer and
 * the repository threat model, which places local concurrent filesystem
 * attackers out of scope.
 *
 * @param {string} target   absolute path to write
 * @param {string} contents file contents (utf-8)
 * @param {{ markerAware?: boolean }} [opts]
 * @throws {Error} when the write is refused
 */
export function writeGeneratedSibling(target, contents, { markerAware = true } = {}) {
    let st = null;
    try {
        st = lstatSync(target);
    } catch (err) {
        // FAIL CLOSED. Only "there is genuinely nothing here" authorizes a
        // create. Any other metadata failure (EACCES, EPERM, ELOOP, EIO…)
        // means we could NOT prove the destination is safe, and proceeding
        // would truncate whatever is actually there.
        if (!err || err.code !== "ENOENT") {
            throw new Error(
                `refusing to write generated output: could not inspect the destination\n` +
                `    ${target}\n  ${err && err.code ? err.code : err}`,
            );
        }
        st = null;
    }

    if (st) {
        if (st.isSymbolicLink()) {
            throw new Error(
                `refusing to write generated output through a symlink:\n    ${target}\n` +
                `  this path is a symbolic link; writing would modify its target instead of ` +
                `creating a compiled sibling.\n  Remove the link or disable emitDts.`,
            );
        }
        if (!st.isFile()) {
            throw new Error(
                `refusing to write generated output over a non-regular file:\n    ${target}`,
            );
        }
        // A file with more than one name is a HARDLINK: truncating it rewrites
        // every other name too, and lstat cannot tell us where those are. The
        // marker gate alone is not enough here because the shared contents may
        // legitimately (or maliciously) carry the marker.
        if (typeof st.nlink === "number" && st.nlink > 1) {
            throw new Error(
                `refusing to write generated output to a hard-linked file:\n    ${target}\n` +
                `  it has ${st.nlink} names, so writing would rewrite the other ones too.\n` +
                `  Break the link or disable emitDts.`,
            );
        }
        // P5: the marker/ownership check AND the write happen on ONE handle
        // inside overwriteVerified — open (no truncate) → fstat → verify marker
        // → ftruncate → write — so a symlink/file swapped in after this lstat
        // can neither redirect the write nor be truncated before it is proven
        // ours.
        overwriteVerified(target, contents, markerAware);
        return;
    }

    // Nothing at the destination: create EXCLUSIVELY. `wx` fails with EEXIST
    // rather than following a link that appeared between the lstat and here,
    // and it refuses a DANGLING symlink (which lstat reports, but a racing
    // one would not) instead of creating its target.
    try {
        writeFileSync(target, contents, { flag: "wx" });
    } catch (err) {
        if (err && err.code === "EEXIST") {
            throw new Error(
                `refusing to write generated output: the destination appeared while we were ` +
                `checking it\n    ${target}\n  Re-run the build.`,
            );
        }
        throw err;
    }
}

// ---------------------------------------------------------------------------
// #6 — private per-invocation output directory
// ---------------------------------------------------------------------------

let __tmpSeq = 0;

/**
 * Create a fresh, unique, private directory for one compile invocation. JS port
 * of `procutil.rs::make_private_temp_dir`: exclusive creation (`recursive:
 * false` fails with EEXIST rather than reusing a planted directory) and mode
 * 0700 so other local users cannot read or plant files inside it.
 *
 * The caller compiles into this directory (`pyths compile -o <dir>/mod.js`) so
 * NO transient file is ever created — or deleted — beside the user's source.
 *
 * @param {string} tag short label embedded in the directory name
 * @returns {string} absolute path to the created directory
 */
export function makePrivateTempDir(tag) {
    const base = tmpdir();
    for (let attempt = 0; attempt < 64; attempt += 1) {
        const name = `pyths-${tag}-${process.pid}-${__tmpSeq++}-${Date.now()}-${
            Math.random().toString(36).slice(2, 10)
        }-${attempt}`;
        const dir = join(base, name);
        try {
            mkdirSync(dir, { recursive: false, mode: 0o700 });
            return dir;
        } catch (err) {
            if (err && err.code === "EEXIST") continue;
            throw err;
        }
    }
    throw new Error("could not create a unique private temp directory after 64 attempts");
}

/** Best-effort recursive removal of a directory created by `makePrivateTempDir`. */
export function removePrivateTempDir(dir) {
    try {
        rmSync(dir, { recursive: true, force: true });
    } catch {
        /* best effort — a leftover temp dir is not worth failing a build over */
    }
}

// ---------------------------------------------------------------------------
// #1 — absolute, PATH-only compiler resolution
// ---------------------------------------------------------------------------

const WINDOWS = process.platform === "win32";

/** PATHEXT list on Windows (upper/lower both tried), empty elsewhere. */
function executableExtensions() {
    if (!WINDOWS) return [];
    const raw = process.env.PATHEXT || ".COM;.EXE;.BAT;.CMD";
    return raw
        .split(";")
        .map((s) => s.trim())
        .filter((s) => s.length > 0);
}

function isFile(p) {
    try {
        return statSync(p).isFile();
    } catch {
        return false;
    }
}

/**
 * P9: a PATH candidate must be an EXECUTABLE regular file, not merely a file.
 * On POSIX a mode-0644 `pyths` earlier on PATH would otherwise shadow an
 * executable one and fail the spawn with EACCES. Windows has no exec bit —
 * executability is decided by PATHEXT — so any regular file qualifies there.
 */
function isExecutableFile(p) {
    try {
        const s = statSync(p);
        if (!s.isFile()) return false;
        if (WINDOWS) return true;
        return (s.mode & 0o111) !== 0;
    } catch {
        return false;
    }
}

/**
 * P5: overwrite an EXISTING regular file with the ownership check and the write
 * on ONE file handle, so nothing that raced the earlier lstat can redirect or
 * be truncated. Correct ordering (the delta review's requirement): open WITHOUT
 * O_TRUNC (no-follow where supported) → fstat the FD (regular file, nlink === 1)
 * → read the FD and verify the marker → and ONLY THEN ftruncate + write. The
 * file is NEVER truncated before ownership is proven.
 *
 * Returns false without writing if `markerAware` and the content is unchanged.
 * On Windows O_NOFOLLOW is unavailable (EINVAL) and symlink creation is
 * privilege-gated; there we open O_RDWR and rely on the pre-open lstat — a
 * documented residual, not a full close.
 */
function overwriteVerified(target, contents, markerAware) {
    const buf = typeof contents === "string" ? Buffer.from(contents) : contents;
    const noFollow = (!WINDOWS && FS.O_NOFOLLOW) ? FS.O_NOFOLLOW : 0;
    let fd;
    try {
        // O_RDWR (read for the marker, write for the output); NO O_TRUNC yet.
        fd = openSync(target, FS.O_RDWR | noFollow);
    } catch (err) {
        if (err && (err.code === "ELOOP" || err.code === "EMLINK")) {
            throw new Error(
                `refusing to write generated output through a symlink (swapped in after ` +
                `inspection):\n    ${target}`,
            );
        }
        throw err;
    }
    try {
        const s = fstatSync(fd);
        if (!s.isFile()) {
            throw new Error(
                `refusing to write generated output over a non-regular file:\n    ${target}`,
            );
        }
        // EXACTLY 1: nlink > 1 is a hard link (writing rewrites the other
        // names too); nlink === 0 means the destination was unlinked after our
        // open — this handle is an orphan and "success" would write to a file
        // that no longer exists at the destination (round-3 should-fix).
        if (typeof s.nlink === "number" && s.nlink !== 1) {
            throw new Error(
                `refusing to write generated output to a file with a hard-link count of ` +
                `${s.nlink}:\n    ${target}\n` +
                `  a count above 1 means writing would rewrite the file's other names too; ` +
                `0 means it was unlinked while being inspected.`,
            );
        }
        if (markerAware) {
            // Read the OPENED handle (not the path) to prove ownership.
            const head = Buffer.alloc(Math.min(Number(s.size) || 0, 4096));
            if (head.length > 0) readSync(fd, head, 0, head.length, 0);
            if (!looksPythsGenerated(head.toString("utf-8"))) {
                throw new Error(
                    `refusing to overwrite a file PythScribe did not generate:\n    ${target}\n` +
                    `  it lacks the \`${GENERATED_MARKER}\` marker, so it looks hand-written and ` +
                    `would be lost.\n  Move it aside or disable emitDts.`,
                );
            }
            // Write-if-changed: compare the whole file only when sizes match.
            if (Number(s.size) === buf.length) {
                const whole = Buffer.alloc(buf.length);
                if (buf.length > 0) readSync(fd, whole, 0, buf.length, 0);
                if (whole.equals(buf)) return false;
            }
        }
        // Ownership proven on THIS handle — now it is safe to truncate + write.
        ftruncateSync(fd, 0);
        // Loop until every byte is on the fd: writeSync may return a SHORT
        // write (quota-limited / FUSE / network filesystems), and ignoring the
        // count would silently emit a truncated module (round-3 should-fix).
        let written = 0;
        while (written < buf.length) {
            const n = writeSync(fd, buf, written, buf.length - written, written);
            if (!(n > 0)) {
                throw new Error(
                    `short write to generated output:\n    ${target}\n` +
                    `  wrote ${written} of ${buf.length} bytes before the filesystem stopped ` +
                    `accepting data; the output would be truncated.`,
                );
            }
            written += n;
        }
        return true;
    } finally {
        closeSync(fd);
    }
}

/**
 * Is `s` a BARE program name — no directory separator, and (on Windows) no
 * `:` (drive-relative `C:evil.exe` and NTFS ADS `prog:ads` syntax)? Anything
 * else is treated as a path and must be TRULY absolute. Mirrors
 * `procutil.rs::is_bare_name` (round-6).
 *
 * @param {string} s
 * @returns {boolean}
 */
function isBareName(s) {
    if (s.includes("/") || s.includes("\\")) return false;
    if (WINDOWS && s.includes(":")) return false;
    return s !== "" && s !== "." && s !== "..";
}

/**
 * Truly absolute: anchored independently of BOTH the cwd and the current
 * drive. Node's win32 `isAbsolute` accepts rooted-but-driveless paths
 * (`\evil.exe`), which resolve against the CURRENT drive — refuse those;
 * require a drive root (`C:\…`) or a UNC/verbatim prefix (`\\server\…`,
 * `\\?\C:\…`). Mirrors Rust `Path::is_absolute` semantics.
 *
 * #442 Rust parity — Rust's `std::path` accepts BOTH separators inside a
 * UNC prefix: `//server/share/x`, `\\server/share/x`, `/\server\share\x`
 * all parse as `Prefix::UNC("server", "share")` and are absolute on
 * Windows, so the CLI (`procutil.rs::resolve_program`) honors them. The
 * old `p.startsWith("\\\\")` test only recognized the pure-backslash
 * spelling — a forward-slash UNC override the Rust side accepts was
 * refused here. It was ALSO over-broad the other way: Rust requires a
 * non-empty server component, ONE separator, and a non-empty share
 * (`\\server`, `\\server\`, `\\server\\share`, `//server/`, `///a/b` are
 * all NOT absolute — they parse as RootDir, i.e. current-drive-relative).
 * The regex below encodes exactly that shape, separator-agnostically:
 * two leading separators (any mix), a non-empty server, one separator, a
 * non-empty share start. Verbatim (`\\?\C:\x`) and device-namespace
 * (`\\.\COM1`) prefixes fit the same shape (server `?` / `.`) and stay
 * accepted, matching Rust.
 *
 * @param {string} p
 * @returns {boolean}
 */
function isTrulyAbsolute(p) {
    if (!isAbsolute(p)) return false;
    if (!WINDOWS) return true;
    return /^[a-zA-Z]:[\\/]/.test(p) || /^[\\/]{2}[^\\/]+[\\/][^\\/]/.test(p);
}

/**
 * `which`-style lookup over the PATH environment variable's directories ONLY.
 *
 * SECURITY (#1, CWE-426): empty PATH elements and a literal `.` element both
 * mean "the current directory" to the platform loader, which is exactly what a
 * hostile repository needs to have its own `pyths.exe` selected. Both are
 * skipped here, mirroring `procutil.rs::search_path`. Relative PATH elements
 * are skipped for the same reason — only TRULY absolute directories (drive
 * root / UNC on Windows, never rooted-driveless) are consulted, so every hit
 * is an absolute path.
 *
 * A non-bare `name` never reaches the PATH loop: it is honoured only as a
 * truly absolute path to an executable file (mirrors
 * `procutil.rs::search_path`, round-6).
 *
 * @param {string} name bare program name (no directory separators)
 * @returns {string|null} absolute path, or null when not found
 */
export function searchPath(name) {
    if (!isBareName(name)) {
        return isTrulyAbsolute(name) && isExecutableFile(name) ? name : null;
    }
    const pathVar = process.env.PATH || process.env.Path;
    if (!pathVar) return null;
    const exts = executableExtensions();
    // P8: a name that ALREADY carries an executable extension (`pyths.exe`,
    // `pyths.cmd`) must be tried DIRECTLY — appending PATHEXT would look for
    // `pyths.exe.EXE`. Check a FIXED set, NOT PATHEXT: with `PATHEXT=.CMD` a
    // real `pyths.exe` must still resolve.
    const KNOWN_EXE = [".exe", ".cmd", ".bat", ".com"];
    const alreadyExe =
        WINDOWS && KNOWN_EXE.some((e) => name.toLowerCase().endsWith(e));
    for (const raw of pathVar.split(delimiter)) {
        const dir = raw.trim();
        // SECURITY: "" and "." are the current directory; a relative element
        // resolves against it. Never search any of them.
        if (dir === "" || dir === "." || !isTrulyAbsolute(dir)) continue;
        if (alreadyExe) {
            const cand = join(dir, name);
            if (isExecutableFile(cand)) return cand;
            continue;
        }
        // On Windows a PATHEXT candidate must be tried FIRST. npm installs an
        // extensionless POSIX shell shim (`pyths`) beside `pyths.cmd`, and the
        // extensionless one is NOT executable by CreateProcess — preferring it
        // would hand `execFileSync` a shell script and fail (or, worse, be
        // treated as a native image). Windows itself resolves by PATHEXT.
        for (const ext of exts) {
            const cand = join(dir, name + ext);
            if (isExecutableFile(cand)) return cand;
        }
        const direct = join(dir, name);
        // Only trust an extensionless hit where the OS would: never on Windows.
        // P9: and only when it is actually executable.
        if (!WINDOWS && isExecutableFile(direct)) return direct;
    }
    return null;
}

/**
 * Locate the `bin/pyths.js` launcher inside an installed `pythscribe` package.
 * The plugins declare `pythscribe` as a direct dependency, so this resolves
 * from the plugin's own location for every normal install — no PATH, no cwd,
 * no shell shim involved, and it is the ONLY form that works on Windows (npm's
 * `node_modules/.bin/pyths.cmd` shim cannot be run by `execFileSync`, which
 * rejects `.cmd`/`.bat` without `shell: true` since CVE-2024-27980).
 *
 * @returns {string|null} absolute path to `bin/pyths.js`, or null
 */
export function findBundledLauncher() {
    try {
        const req = createRequire(import.meta.url);
        const pkgJson = req.resolve("pythscribe/package.json");
        const launcher = join(dirname(pkgJson), "bin", "pyths.js");
        return isFile(launcher) ? launcher : null;
    } catch {
        return null;
    }
}

/**
 * An npm `.bin` shim (`pyths.cmd` / `pyths.ps1` / extensionless `pyths` sh
 * script) cannot be spawned by `execFileSync`. Map it back to the real
 * launcher: `<x>/node_modules/.bin/pyths.cmd` -> `<x>/node_modules/pythscribe/bin/pyths.js`.
 *
 * @returns {string|null} absolute launcher path, or null
 */
function launcherBesideBinShim(shimPath) {
    const binDir = dirname(shimPath);
    for (const rel of [
        // local install: <x>/node_modules/.bin/pyths.cmd
        ["..", "pythscribe", "bin", "pyths.js"],
        // global npm on Windows: <prefix>/pyths.cmd with the package under
        // <prefix>/node_modules/pythscribe
        ["node_modules", "pythscribe", "bin", "pyths.js"],
        // global npm on unix: <prefix>/bin/pyths -> ../lib/node_modules/...
        ["..", "lib", "node_modules", "pythscribe", "bin", "pyths.js"],
    ]) {
        const launcher = resolve(binDir, ...rel);
        if (isFile(launcher)) return launcher;
    }
    return null;
}

/**
 * Resolve the PythScribe compiler to an ABSOLUTE command plus any leading
 * arguments. Never returns a bare name, so the platform's search order — which
 * can include the current directory — is never consulted (#1, CWE-426).
 *
 * Resolution order:
 *   1. explicit `pythsBin` plugin option        (user-set, trusted)
 *   2. `PYTHS_BIN` env                           (user-set, trusted)
 *   3. `PYTHS_DEV_BIN` opt-in local cargo build  (existence check only, no exec)
 *   4. the `pythscribe` npm package's launcher   (a direct dependency)
 *   5. `pyths` on PATH, absolute, cwd never searched
 *
 * Options 1 and 2 are ABSOLUTE-ONLY when they carry a path (final round,
 * mirroring `procutil.rs::resolve_program`): a relative value
 * (`PYTHS_BIN=./evil.exe`) resolves against the current directory — the
 * exact CWE-426 cwd-execution hole this module closes, and an env var
 * carried into a hostile checkout would run its planted compiler — so it is
 * refused with an error, never cwd-resolved and never silently downgraded
 * to a different compiler. A bare NAME in either is PATH-resolved (absolute
 * PATH dirs only), not cwd-resolved. Windows drive-relative (`C:evil.exe`)
 * and rooted-driveless (`\evil.exe`) values are refused too.
 *
 * @param {{ pythsBin?: string|null }} [opts]
 * @returns {{ command: string, prefixArgs: string[] }}
 * @throws {Error} when no compiler can be located
 */
export function resolvePythsCommand({ pythsBin = null } = {}) {
    const explicit = pythsBin || process.env.PYTHS_BIN || null;
    if (explicit) {
        if (!isBareName(explicit)) {
            if (!isTrulyAbsolute(explicit)) {
                throw new Error(
                    `PYTHS_BIN / pythsBin must be an ABSOLUTE path or a bare program name, ` +
                    `got "${explicit}".\n` +
                    `  A relative (or drive-relative) value resolves against the current ` +
                    `working directory, re-opening the cwd-execution hole (CWE-426).`,
                );
            }
            // `resolve` of an already-absolute path only normalizes — the
            // cwd cannot influence it.
            const abs = resolve(explicit);
            if (isFile(abs)) return asCommand(abs);
            throw new Error(
                `PythScribe compiler not found at the configured path: ${explicit}`,
            );
        }
        const found = searchPath(explicit);
        if (found) return asCommand(found);
        throw new Error(
            `PythScribe compiler "${explicit}" was not found on PATH.\n` +
            `  Set PYTHS_BIN to an absolute path, or install the \`pythscribe\` package.`,
        );
    }

    // `PYTHS_DEV_BIN` is the opt-in for compiler developers running against a
    // local cargo build. It used to be a BOOLEAN that made the plugin probe
    // `./target/{release,debug}/pyths` under the CURRENT WORKING DIRECTORY —
    // which re-opened the very cwd-execution hole this module closes the moment
    // a developer carried the variable into a hostile checkout. It is now an
    // explicit PATH to the binary (or to a cargo target dir), validated before
    // use. The legacy boolean form is refused with a message telling the user
    // what to set instead.
    const devBin = process.env.PYTHS_DEV_BIN;
    if (devBin && devBin !== "1" && devBin.toLowerCase() !== "true") {
        // P1: a RELATIVE PYTHS_DEV_BIN resolves against the current directory,
        // which is the exact cwd-execution hole (CWE-426) this module closes —
        // carrying `PYTHS_DEV_BIN=target/release/pyths` into a hostile checkout
        // would run its planted compiler. Require an absolute path.
        if (!isTrulyAbsolute(devBin)) {
            throw new Error(
                `PYTHS_DEV_BIN must be an ABSOLUTE path, got "${devBin}".\n` +
                `  A relative value resolves against the current working directory, ` +
                `re-opening the cwd-execution hole (CWE-426).\n` +
                `  Use an absolute path to the pyths binary or its cargo target dir.`,
            );
        }
        const p = resolve(devBin);
        if (isFile(p)) return asCommand(p);
        for (const rel of ["pyths", "pyths.exe", "release/pyths", "release/pyths.exe",
                           "debug/pyths", "debug/pyths.exe"]) {
            const cand = resolve(p, rel);
            if (isFile(cand)) return { command: cand, prefixArgs: [] };
        }
        throw new Error(
            `PYTHS_DEV_BIN=${devBin} does not point at a pyths binary or a cargo target dir.`,
        );
    }
    if (devBin) {
        throw new Error(
            "PYTHS_DEV_BIN is now a PATH, not a flag.\n" +
            "  Probing `./target/release/pyths` relative to the current directory allowed a " +
            "hostile checkout to supply the compiler (CWE-426).\n" +
            "  Set PYTHS_DEV_BIN=/abs/path/to/target/release/pyths (or to the target dir).",
        );
    }

    const bundled = findBundledLauncher();
    if (bundled) return { command: process.execPath, prefixArgs: [bundled] };

    const onPath = searchPath("pyths");
    if (onPath) return asCommand(onPath);

    throw new Error(
        "PythScribe compiler not found.\n" +
        "  Install it with `npm i -D pythscribe`, or set PYTHS_BIN to an absolute path.",
    );
}

/**
 * Turn a resolved absolute file into a spawnable `{ command, prefixArgs }`.
 * A `.js` launcher (or a `.cmd`/`.bat`/`.ps1` npm shim, which `execFileSync`
 * refuses to run) is routed through the current Node executable.
 */
function asCommand(abs) {
    const lower = abs.toLowerCase();
    if (lower.endsWith(".js") || lower.endsWith(".mjs") || lower.endsWith(".cjs")) {
        return { command: process.execPath, prefixArgs: [abs] };
    }
    if (lower.endsWith(".cmd") || lower.endsWith(".bat") || lower.endsWith(".ps1")) {
        const launcher = launcherBesideBinShim(abs);
        if (launcher) return { command: process.execPath, prefixArgs: [launcher] };
        throw new Error(
            `refusing to spawn the shell shim ${abs}\n` +
            `  Node cannot execute .cmd/.bat without a shell. Install the \`pythscribe\` ` +
            `package (which ships bin/pyths.js) or set PYTHS_BIN to the native binary.`,
        );
    }
    return { command: abs, prefixArgs: [] };
}

/**
 * Run the compiler.
 *
 * SECURITY (#1, CWE-426): this is the LAST line of defence and it fails closed.
 * `execFileSync` resolves a bare or relative program name through the platform
 * search — which can include the current directory — so a command that is not
 * an absolute path is refused here regardless of how it was obtained. Any call
 * site that reaches this with a bare name (e.g. a consumer wiring
 * `next-plugin-pyths/loader.js` up by hand and passing `pythsBin: "pyths"`) is
 * a bug, and it is caught rather than executed.
 *
 * `killSignal: "SIGKILL"` is used with the timeout so a wedged compiler is
 * actually torn down rather than left holding the private output directory.
 *
 * @param {{ command: string, prefixArgs: string[] }} cmd
 * @param {string[]} args
 * @returns {string} stdout
 */
export function runPyths(cmd, args) {
    if (!cmd || typeof cmd.command !== "string" || !isAbsolute(cmd.command)) {
        throw new Error(
            `refusing to spawn the compiler by a non-absolute name: ${cmd && cmd.command}\n` +
            `  A bare or relative program name is resolved by the platform, whose search can ` +
            `include the current directory (CWE-426).\n` +
            `  Resolve it with resolvePythsCommand() first.`,
        );
    }
    return execFileSync(cmd.command, [...(cmd.prefixArgs || []), ...args], {
        encoding: "utf-8",
        timeout: 30000,
        killSignal: "SIGKILL",
    });
}

/** Re-export for call sites that only need an existence check. */
export { existsSync };
