// Livermore kernel performance table (§7.1, Axon Table-4 style):
// per kernel, time CPython vs compiled JS vs compiled JS+WASM (the
// auto-routed kernel) at a fixed scaled repetition count, and record
// whether the auto-router's choice (WASM for pure-numeric) is the
// empirical winner.
//
// Methodology: whole-process wall clock, median of 3 runs, minus the
// per-backend startup baseline (hello-world) measured the same way —
// the residual is kernel compute. Coarse but honest and reproducible;
// numbers land in livermore-results.md + one ablation-ledger row.
//
// NOT in CI (correctness runs there — tests/differential/livermore).
// Regenerate:  node examples/cloudflare-bench/bench/livermore/perf.mjs

import { spawnSync } from "node:child_process";
import { promises as fs, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..", "..");
const KERNEL_DIR = path.join(REPO_ROOT, "tests", "differential", "livermore");
const PYTHS_BIN = process.env.PYTHS_BIN ?? path.join(
    REPO_ROOT, "target", "release",
    process.platform === "win32" ? "pyths.exe" : "pyths");
const RUNTIME_INDEX = path.join(REPO_ROOT, "runtime", "src", "index.js");
const SCRATCH = path.join(__dirname, ".scratch");
await fs.mkdir(SCRATCH, { recursive: true });

// Repetition scale: the correctness files use tiny loop counts; multiply
// the final `loop` argument so compute dominates process startup.
const SCALE = 400;

function timeCmd(cmd, args, cwd) {
    const t0 = process.hrtime.bigint();
    const r = spawnSync(cmd, args, { encoding: "utf8", cwd });
    const ms = Number(process.hrtime.bigint() - t0) / 1e6;
    if (r.status !== 0) throw new Error(`${cmd} failed: ${r.stderr}`);
    return ms;
}

function median3(f) {
    const xs = [f(), f(), f()].sort((a, b) => a - b);
    return xs[1];
}

function rewire(js) {
    const runtimeUrl = pathToFileURL(RUNTIME_INDEX).href;
    return js.replace(/from\s+["']pyths-runtime["']/g, `from "${runtimeUrl}"`);
}

// Startup baselines.
const helloPy = path.join(SCRATCH, "hello.py");
writeFileSync(helloPy, "print(1)\n");
const helloJs = path.join(SCRATCH, "hello.mjs");
writeFileSync(helloJs, "console.log(1)\n");
const basePy = median3(() => timeCmd("python", [helloPy]));
const baseNode = median3(() => timeCmd("node", [helloJs]));

const files = (await fs.readdir(KERNEL_DIR)).filter((f) => /^k\d\d_.*\.ps$/.test(f)).sort();
const rows = [];
for (const f of files) {
    const id = f.replace(/\.ps$/, "");
    const src = readFileSync(path.join(KERNEL_DIR, f), "utf8");
    // Scale the driver call's last argument: print(repr(kXX(N, LOOP)))
    const scaled = src.replace(
        /print\(repr\((\w+)\((\d+), (\d+)\)\)\)/,
        (_m, fn, n, loop) => `print(repr(${fn}(${n}, ${Number(loop) * SCALE})))`);
    const psPath = path.join(SCRATCH, f);
    writeFileSync(psPath, scaled);

    // CPython
    const pyMs = median3(() => timeCmd("python", [psPath])) - basePy;

    // Compiled JS
    const jsOut = path.join(SCRATCH, `${id}.js.js`);
    spawnSync(PYTHS_BIN, ["compile", psPath, "--target", "js", "-o", jsOut, "--quiet"],
        { encoding: "utf8", env: { ...process.env, PYTHS_NO_CACHE: "1" } });
    const jsMjs = path.join(SCRATCH, `${id}.js.run.mjs`);
    writeFileSync(jsMjs, rewire(readFileSync(jsOut, "utf8")));
    const jsMs = median3(() => timeCmd("node", [jsMjs], SCRATCH)) - baseNode;

    // Compiled JS+WASM (kernel auto-routed to WASM)
    const wOut = path.join(SCRATCH, `${id}.wasm.js`);
    spawnSync(PYTHS_BIN, ["compile", psPath, "--target", "js+wasm", "-o", wOut, "--quiet"],
        { encoding: "utf8", env: { ...process.env, PYTHS_NO_CACHE: "1" } });
    const wMjs = path.join(SCRATCH, `${id}.wasm.run.mjs`);
    writeFileSync(wMjs, rewire(readFileSync(wOut, "utf8")));
    // #358: the glue embeds exact JS twins importing the runtime — rewire it too.
    const wGlue = wOut.replace(/\.js$/, ".glue.js");
    try { writeFileSync(wGlue, rewire(readFileSync(wGlue, "utf8"))); } catch {}
    const wasmMs = median3(() => timeCmd("node", [wMjs], SCRATCH)) - baseNode;

    const winner = wasmMs < jsMs ? "wasm" : "js";
    rows.push({ id, pyMs, jsMs, wasmMs, winner });
    console.log(`${id}: py ${pyMs.toFixed(1)}ms  js ${jsMs.toFixed(1)}ms  wasm ${wasmMs.toFixed(1)}ms  -> ${winner}`);
}

// ---- Emit the results table ----
const wasmWins = rows.filter((r) => r.winner === "wasm").length;
let md = `# Livermore kernel performance — CPython vs compiled JS vs auto-routed WASM

*Generated by \`bench/livermore/perf.mjs\` (median of 3 whole-process runs,
startup baseline subtracted, loop counts x${SCALE} the correctness suite).
Correctness for every row is enforced separately in CI
(\`tests/differential/livermore/run.mjs\` — byte-identical output on all
three backends). Machine-dependent: regenerate locally before citing.*

| Kernel | CPython (ms) | JS (ms) | WASM (ms) | JS/CPython | WASM/JS | Faster backend |
|---|--:|--:|--:|--:|--:|---|
`;
for (const r of rows) {
    md += `| ${r.id} | ${r.pyMs.toFixed(1)} | ${r.jsMs.toFixed(1)} | ${r.wasmMs.toFixed(1)} | ${(r.pyMs / r.jsMs).toFixed(1)}x | ${(r.jsMs / r.wasmMs).toFixed(2)}x | ${r.winner} |\n`;
}
md += `\nWASM wins ${wasmWins}/${rows.length} kernels at this scale. Startup overhead dominates the light kernels (the Axon finding); the heavy loop nests are where the WASM path pays.\n`;
writeFileSync(path.join(__dirname, "livermore-results.md"), md);

// ---- Ledger row ----
const gitRev = spawnSync("git", ["rev-parse", "--short", "HEAD"],
    { encoding: "utf8", cwd: REPO_ROOT }).stdout.trim();
const row = {
    exp_id: "livermore_v1",
    date: new Date().toISOString().slice(0, 10),
    commit: gitRev,
    corpus: "tests/differential/livermore (24 LFK kernels)",
    condition: "cpython vs js vs js+wasm",
    axis: { phase: "perf", oracle: "cpython-differential (CI)" },
    metric: {
        wasm_wins: wasmWins,
        kernels: rows.length,
        js_over_cpython_median: rows.map(r => r.pyMs / r.jsMs).sort((a, b) => a - b)[Math.floor(rows.length / 2)],
        wasm_over_js_median: rows.map(r => r.jsMs / r.wasmMs).sort((a, b) => a - b)[Math.floor(rows.length / 2)],
    },
    n: 3,
    raw_ref: "bench/livermore/livermore-results.md",
};
const ledger = path.join(__dirname, "..", "ablations", "ledger.jsonl");
await fs.appendFile(ledger, JSON.stringify(row) + "\n");
console.log(`\nwrote livermore-results.md + ledger row livermore_v1 (${wasmWins}/${rows.length} wasm wins)`);
