// Memory metric (dual-track benchmark dashboard, metric 7/7):
// process.memoryUsage() snapshots around module load for the compiled
// large-sample fixtures, per track. Each measurement runs in a FRESH
// node child (heap state from prior loads would pollute in-process
// numbers); rss/heapUsed deltas are child-reported.
//
// Regenerate:  node examples/cloudflare-bench/bench/measure_memory.mjs

import { spawnSync } from "node:child_process";
import { promises as fs, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const PYTHS_BIN = process.env.PYTHS_BIN ?? path.join(
    REPO_ROOT, "target", "release",
    process.platform === "win32" ? "pyths.exe" : "pyths");
const RUNTIME_INDEX = path.join(REPO_ROOT, "runtime", "src", "index.js");
const FIXTURES = ["dashboard_500", "app_1000"];
const SAMPLES = path.join(REPO_ROOT, "examples", "cloudflare-bench", "large-samples", "pythscribe");
const SCRATCH = path.join(__dirname, ".memscratch");
await fs.mkdir(SCRATCH, { recursive: true });

function measure(moduleUrl) {
    const probe = path.join(SCRATCH, "probe.mjs");
    writeFileSync(probe, `
const before = process.memoryUsage();
await import(${JSON.stringify(moduleUrl)});
global.gc && global.gc();
const after = process.memoryUsage();
console.log(JSON.stringify({
  rss: after.rss - before.rss,
  heapUsed: after.heapUsed - before.heapUsed,
}));
`);
    const r = spawnSync("node", ["--expose-gc", probe], { encoding: "utf8" });
    if (r.status !== 0) throw new Error(r.stderr);
    return JSON.parse(r.stdout.trim().split("\n").pop());
}

const kib = (b) => (b / 1024).toFixed(0);
let md = `# Memory footprint — module-load deltas (fresh node child, --expose-gc)

*Generated by \`bench/measure_memory.mjs\`. Delta = process.memoryUsage()
after importing the compiled module (post-GC) minus before. Machine- and
node-version-dependent; regenerate before citing.*

| Fixture | rss Δ (KiB) | heapUsed Δ (KiB) |
|---|--:|--:|
`;
for (const f of FIXTURES) {
    const ps = path.join(SAMPLES, `${f}.ps`);
    const js = path.join(SCRATCH, `${f}.js`);
    const compile = spawnSync(PYTHS_BIN, ["compile", ps, "-o", js, "--quiet"],
        { encoding: "utf8", env: { ...process.env, PYTHS_NO_CACHE: "1" } });
    if (compile.status !== 0) throw new Error(compile.stderr);
    const clonesModules = path.join(REPO_ROOT, "examples", "clones", "node_modules");
    const rewired = readFileSync(js, "utf8")
        .replace(/from\s+["']pyths-runtime\/asyncio["']/g, `from "${pathToFileURL(path.join(REPO_ROOT, "runtime", "asyncio.js")).href}"`)
        .replace(/from\s+["']pyths-runtime\/react["']/g, `from "${pathToFileURL(RUNTIME_INDEX).href}"`)
        .replace(/from\s+["']pyths-runtime["']/g, `from "${pathToFileURL(RUNTIME_INDEX).href}"`)
        .replace(/from\s+["']react["']/g, `from "${pathToFileURL(path.join(clonesModules, "react", "index.js")).href}"`);
    const mjs = path.join(SCRATCH, `${f}.run.mjs`);
    writeFileSync(mjs, rewired);
    const m = measure(pathToFileURL(mjs).href);
    md += `| ${f} (compiled .ps→JS + runtime) | ${kib(m.rss)} | ${kib(m.heapUsed)} |\n`;
    console.log(`${f}: rss +${kib(m.rss)} KiB, heap +${kib(m.heapUsed)} KiB`);
}
md += `\nNo interpreter ships: the delta is the compiled module + the pyths-runtime helpers it imports.\n`;
await fs.writeFile(path.join(__dirname, "memory-results.md"), md);
console.log("wrote memory-results.md");
