// LOC metric (dual-track benchmark dashboard, metric 5/7): source lines
// per track for the clone corpus — .tsx (React oracle) vs .ps vs .psc.
// cloc-style counting without the cloc dependency: non-blank, non-
// comment-only lines (// or # by first non-ws char; JSX comments and
// block comments counted approximately — the same rule applied to all
// three tracks, so the RATIO is fair even if absolute counts differ
// from cloc by a line or two).
//
// Regenerate:  node examples/cloudflare-bench/bench/measure_loc.mjs

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SHARED = path.resolve(__dirname, "..", "..", "clones", "shared");

function countLoc(src, ext) {
    let loc = 0;
    let inBlock = false;
    for (const raw of src.split("\n")) {
        const line = raw.trim();
        if (line === "") continue;
        if (ext === ".tsx") {
            if (inBlock) {
                if (line.includes("*/")) inBlock = false;
                continue;
            }
            if (line.startsWith("//")) continue;
            if (line.startsWith("/*")) {
                if (!line.includes("*/")) inBlock = true;
                continue;
            }
        } else if (line.startsWith("#")) {
            continue;
        }
        loc++;
    }
    return loc;
}

async function walk(dir, out) {
    for (const e of await fs.readdir(dir, { withFileTypes: true })) {
        const p = path.join(dir, e.name);
        if (e.isDirectory()) await walk(p, out);
        else out.push(p);
    }
}

const files = [];
await walk(SHARED, files);
const tracks = { ".tsx": 0, ".ps": 0, ".psc": 0 };
const perComponent = new Map();
for (const f of files) {
    const ext = path.extname(f);
    if (!(ext in tracks)) continue;
    if (f.endsWith(".test.tsx")) continue; // tests aren't app source
    const loc = countLoc(await fs.readFile(f, "utf8"), ext);
    tracks[ext] += loc;
    const stem = path.basename(f, ext);
    if (!perComponent.has(stem)) perComponent.set(stem, {});
    perComponent.get(stem)[ext] = loc;
}

let md = `# LOC per track — clone corpus (non-blank, non-comment lines)

*Generated by \`bench/measure_loc.mjs\`. Only components present in all
three tracks are included in the per-component table; totals cover every
track file under \`examples/clones/shared/\` (tests excluded).*

| Component | .tsx | .ps | .psc | .ps/.tsx | .psc/.tsx |
|---|--:|--:|--:|--:|--:|
`;
const rows = [...perComponent.entries()]
    .filter(([, v]) => v[".tsx"] && v[".ps"] && v[".psc"])
    .sort(([a], [b]) => a.localeCompare(b));
for (const [stem, v] of rows) {
    md += `| ${stem} | ${v[".tsx"]} | ${v[".ps"]} | ${v[".psc"]} | ${(v[".ps"] / v[".tsx"] * 100).toFixed(0)}% | ${(v[".psc"] / v[".tsx"] * 100).toFixed(0)}% |\n`;
}
md += `| **total (3-track components)** | **${rows.reduce((s, [, v]) => s + v[".tsx"], 0)}** | **${rows.reduce((s, [, v]) => s + v[".ps"], 0)}** | **${rows.reduce((s, [, v]) => s + v[".psc"], 0)}** | | |\n`;
md += `\nAll-file totals: .tsx ${tracks[".tsx"]}, .ps ${tracks[".ps"]}, .psc ${tracks[".psc"]} — .ps is ${(tracks[".ps"] / tracks[".tsx"] * 100).toFixed(0)}% of the React source, .psc ${(tracks[".psc"] / tracks[".tsx"] * 100).toFixed(0)}%.\n`;
await fs.writeFile(path.join(__dirname, "loc-results.md"), md);
console.log(md.split("\n").slice(-2).join("\n"));
