"""constrained_focused.py — Tier 2 focused constrained-only run.

Runs SynCode grammar_strict against grammar/pyths.lark (via the pyths_syncode.lark
wrapper generated by constrained_gen_demo.ensure_syncode_grammar) with opp=False
(non-opportunistic / strict) and a larger token budget so programs can COMPLETE
rather than truncate. Re-verifies each output with the canonical pyths.lark
acceptor. Requires the mask store already built/cached by constrained_gen_demo.py.

    python examples/constrained-decoding/constrained_focused.py

Observed finding (documented in README.md): SynCode's incremental parser can
throw on our grammar mid-decode and logs "Parsing failed! Falling back to
unconstrained decoding" — so enforcement is not robust on this integration,
even though it produces a clean valid program when it does hold (sample 0).
"""
import warnings, os, json, subprocess, sys, re
warnings.filterwarnings("ignore")
ROOT=os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HERE=os.path.dirname(os.path.abspath(__file__))
PYTHS=os.path.join(ROOT,"target","release","pyths.exe")
GRAMMAR=os.path.join(ROOT,"grammar","pyths.lark")
SYN=os.path.join(HERE,"pyths_syncode.lark")
import lark
from lark.indenter import PythonIndenter
acc=lark.Lark.open(GRAMMAR,parser="lalr",postlex=PythonIndenter(),start="file_input",maybe_placeholders=False)
def g_ok(s):
    try: acc.parse(s+"\n"); return True
    except Exception: return False
def strip_fence(t):
    t=t.strip()
    m=re.search(r"```[a-zA-Z0-9_]*\n?(.*?)```",t,re.DOTALL)
    return m.group(1).strip() if m else t
from syncode import Syncode
PROMPT=("Write a single PythScribe function named `square(n)` that returns n*n. "
        "Then on the next line write `result = square(7)`. Output only code.")
llm=Syncode(model="Qwen/Qwen2.5-Coder-0.5B-Instruct", mode="grammar_strict",
            device="cpu", quantize=False, parse_output_only=True, indent=True,
            grammar=SYN, opp=False, max_new_tokens=160, do_sample=True,
            temperature=0.7, seed=7)
N=6; ok=0; samples=[]
for i in range(N):
    try:
        out=llm.infer(PROMPT); out=out[0] if isinstance(out,list) else out
    except Exception as e:
        out=f"<<infer error: {type(e).__name__}: {e}>>"
    code=strip_fence(out); p=g_ok(code); ok+=1 if p else 0
    samples.append({"i":i,"grammar_ok":p,"code":code})
    print(f"[{i}] grammar_ok={p}\n    "+code.replace("\n","\n    "))
print(f"\nconstrained (opp=False, max_new=160): parses {ok}/{N}  err_rate={(N-ok)/N:.3f}")
json.dump({"n":N,"parses":ok,"syntax_error_rate":(N-ok)/N,"samples":samples},
          open(os.path.join(HERE,"constrained_focused_result.json"),"w"),indent=2)
