# Type stubs for `lucide-react` — open-source icon library.
#
# Each icon is a React component accepting standard SVG props plus
# a `size`, `color`, and `strokeWidth`. Users typically import a
# specific icon by name; the codegen routes `lucide_react` through
# the React-module path so snake_case import aliases work.
#
# The bundled stub declares the surface shape but doesn't enumerate
# every icon (1000+) — unrecognized names fall back to `Type::Any`.

from typing import Any, Callable, Optional


class LucideIcon:
    pass


# Common icons people reach for most often.
def ChevronDown(props: Any) -> Any:
    ...
def ChevronUp(props: Any) -> Any:
    ...
def ChevronLeft(props: Any) -> Any:
    ...
def ChevronRight(props: Any) -> Any:
    ...
def Check(props: Any) -> Any:
    ...
def X(props: Any) -> Any:
    ...
def Menu(props: Any) -> Any:
    ...
def Search(props: Any) -> Any:
    ...
def User(props: Any) -> Any:
    ...
def Settings(props: Any) -> Any:
    ...
def Home(props: Any) -> Any:
    ...
def Plus(props: Any) -> Any:
    ...
def Minus(props: Any) -> Any:
    ...
def Loader(props: Any) -> Any:
    ...
def Loader2(props: Any) -> Any:
    ...
