// @generated by PythScribe — do not edit; regenerate with `pyths compile`.
// Auto-generated by PythScribe compiler — do not edit.
import { __pyF, __reqNum, pyAdd, pyDiv, pyEq } from "./pyths-runtime/index.js";
const __PYTHS_ABI = { abi: 1, list_layout: "pyths-0.2.4-list-v1", array_layout: "pyths-0.2.5-array-v2" };
function __checkPythsAbi(module) {
  const secs = WebAssembly.Module.customSections(module, "pyths.abi");
  if (secs.length !== 1) throw new Error('pythscribe: WASM ABI check failed: expected exactly one `pyths.abi` custom section, found ' + secs.length + ' (this .wasm was not emitted by the pyths compiler that emitted this glue; rebuild the artifact)');
  let got;
  try { got = JSON.parse(new TextDecoder().decode(new Uint8Array(secs[0]))); } catch (e) { throw new Error('pythscribe: WASM ABI check failed: `pyths.abi` section is not valid JSON (' + e.message + ')'); }
  for (const f of ['abi', 'list_layout', 'array_layout']) {
    if (got[f] !== __PYTHS_ABI[f]) throw new Error('pythscribe: WASM ABI mismatch on `' + f + '`: module=' + JSON.stringify(got[f]) + ' glue=' + JSON.stringify(__PYTHS_ABI[f]) + ' -- rebuild the artifact with the matching pyths compiler (a mismatched layout would be read at the wrong width; refused, never silently)');
  }
}
const __wasm = await (async () => {
  const imports = {};
  const url = new URL('./monthly_payment.wasm', import.meta.url);
  const isNode = typeof globalThis.process !== 'undefined'
    && globalThis.process.versions != null
    && typeof globalThis.process.versions.node === 'string';
  let __module;
  if (isNode) {
    const { readFile } = await import('node:fs/promises');
    const { fileURLToPath } = await import('node:url');
    const bytes = await readFile(fileURLToPath(url));
    __module = await WebAssembly.compile(bytes);
  } else if (typeof WebAssembly.compileStreaming === 'function') {
    __module = await WebAssembly.compileStreaming(fetch(url));
  } else {
    const bytes = await fetch(url).then(r => r.arrayBuffer());
    __module = await WebAssembly.compile(bytes);
  }
  __checkPythsAbi(__module);
  const __instance = await WebAssembly.instantiate(__module, imports);
  return __instance.exports;
})();
const __i64ToJs = (v) => (v >= -9007199254740991n && v <= 9007199254740991n ? Number(v) : v);
class __PyFloatW extends Number { get __pyfloat__() { return true; } }
const __f64Box = (v) => (Number.isInteger(v) ? new __PyFloatW(v) : v);
const __f64Arg = (v) => { if (typeof v !== "bigint") return v; const n = Number(v); if (Number.isFinite(n)) return n; const e = new Error("int too large to convert to float"); e.name = "OverflowError"; throw e; };
const __i64Oob = (v) => typeof v === "bigint" && (v > 9223372036854775807n || v < -9223372036854775808n);

// #358: exact JS twins of the WASM-compiled functions. When a call
// would exceed i64 (the `__ovf` flag, or an out-of-range argument),
// the wrapper transparently re-runs it on these arbitrary-precision
// implementations — the WASM fast path never returns a wrapped value.
const __jsfb = (() => {

function monthly_payment(principal, annual_rate_pct, months) {
    if ((months <= 0)) {
        return __pyF(0);
    }
    let r = pyDiv(annual_rate_pct, __pyF(1200));
    if (pyEq(r, __pyF(0))) {
        return pyDiv(principal, months);
    }
    let factor = __pyF(1);
    let base = __pyF((1) + __reqNum(r));
    let i = 0;
    while ((i < months)) {
        factor = __pyF(__reqNum(factor) * __reqNum(base));
        i = pyAdd(i, 1);
    }
    if (pyEq(factor, __pyF(1))) {
        return pyDiv(principal, months);
    }
    return pyDiv(__pyF(__reqNum(__pyF(__reqNum(principal) * __reqNum(r))) * __reqNum(factor)), __pyF(__reqNum(factor) - (1)));
}
monthly_payment.__pyparams__ = ["principal", "annual_rate_pct", "months"];
return { monthly_payment };
})();
const __isWasmFault = (e) => (typeof WebAssembly !== "undefined" && e instanceof WebAssembly.RuntimeError) || e instanceof RangeError;

export function monthly_payment(principal, annual_rate_pct, months) {
  try {
  if (__i64Oob(months)) return __jsfb.monthly_payment(principal, annual_rate_pct, months);
  const __raw = __wasm.monthly_payment(__f64Arg(principal), __f64Arg(annual_rate_pct), (typeof months === "bigint" ? months : BigInt(Math.trunc(months))));
  if (__wasm.__ovf.value) {
    __wasm.__ovf.value = 0;
    return __jsfb.monthly_payment(principal, annual_rate_pct, months);
  }
  return __f64Box(__raw);
  } catch (__e) {
    if (__isWasmFault(__e)) return __jsfb.monthly_payment(principal, annual_rate_pct, months);
    throw __e;
  }
}
monthly_payment.__pyparams__ = ["principal", "annual_rate_pct", "months"];
