use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

use super::output::{self, Verbosity};

pub fn run(
    entry: &str,
    output: Option<&str>,
    minify: bool,
    verbosity: Verbosity,
) -> Result<(), Box<dyn std::error::Error>> {
    let entry_path = Path::new(entry);
    if !entry_path.exists() {
        return Err(format!("Entry file not found: {}", entry).into());
    }

    super::output::info(&format!("Bundling from entry: {}", entry), verbosity);

    // Collect all .ps files in the project
    let base_dir = entry_path.parent().unwrap_or(Path::new("."));
    let mut modules: HashMap<String, String> = HashMap::new();
    let mut runtime_imports: HashSet<String> = HashSet::new();

    // Process entry file and follow local imports
    let mut queue: Vec<PathBuf> = vec![entry_path.to_path_buf()];
    let mut visited: HashSet<PathBuf> = HashSet::new();

    while let Some(file_path) = queue.pop() {
        let canonical = file_path
            .canonicalize()
            .unwrap_or_else(|_| file_path.clone());
        if visited.contains(&canonical) {
            continue;
        }
        visited.insert(canonical);

        let source = std::fs::read_to_string(&file_path)?;
        let filename = file_path.file_stem().unwrap().to_string_lossy().to_string();

        // Parse
        let module = pyths_parser::parse(&source).map_err(|errors| {
            let messages: Vec<String> = errors.iter().map(|e| e.message.clone()).collect();
            format!(
                "Parse error in {}: {}",
                file_path.display(),
                messages.join(", ")
            )
        })?;

        // Collect local imports for dependency following
        for stmt in &module.body {
            if let pyths_syntax::ast::StmtKind::Import { names } = &stmt.kind {
                for alias in names {
                    let local_path = base_dir.join(format!("{}.ps", alias.name.replace('.', "/")));
                    if local_path.exists() {
                        queue.push(local_path);
                    } else {
                        runtime_imports.insert(alias.name.clone());
                    }
                }
            }
            if let pyths_syntax::ast::StmtKind::ImportFrom {
                module: mod_name,
                level,
                ..
            } = &stmt.kind
            {
                // For relative imports, the local source path is computed by
                // climbing `level` ancestors from the importing file's
                // directory, then joining the dotted module path. For absolute
                // imports (level=0), we look under base_dir as before.
                let mut resolution_base = base_dir.to_path_buf();
                if *level > 0 {
                    for _ in 1..*level {
                        if let Some(parent) = resolution_base.parent() {
                            resolution_base = parent.to_path_buf();
                        }
                    }
                }
                let local_path = if mod_name.is_empty() {
                    // `from . import foo` — the module *is* the package dir;
                    // bundle walker can't follow further without per-name
                    // resolution, so skip until that lands.
                    base_dir.join("__init__.ps")
                } else {
                    resolution_base.join(format!("{}.ps", mod_name.replace('.', "/")))
                };
                if local_path.exists() {
                    queue.push(local_path);
                } else {
                    runtime_imports.insert(mod_name.clone());
                }
            }
        }

        // Codegen
        let js = pyths_codegen_js::codegen_inline(&module);
        modules.insert(filename, js);
    }

    // Build bundle
    let mut bundle = String::new();

    // Banner
    bundle.push_str("// PythScribe Bundle — generated by `pyths bundle`\n");
    bundle.push_str("// Entry: ");
    bundle.push_str(entry);
    bundle.push_str("\n\n");

    // Emit modules as IIFEs (inline for now)
    let entry_stem = entry_path
        .file_stem()
        .unwrap()
        .to_string_lossy()
        .to_string();

    // Entry module comes last
    let mut sorted_modules: Vec<(String, String)> = modules
        .into_iter()
        .filter(|(name, _)| *name != entry_stem)
        .collect();
    sorted_modules.sort_by(|a, b| a.0.cmp(&b.0));

    // Non-entry modules wrapped in namespace
    for (name, js) in &sorted_modules {
        bundle.push_str(&format!("// --- Module: {} ---\n", name));
        bundle.push_str(&format!("const {} = (() => {{\n", name));
        // Indent the module code
        for line in js.lines() {
            if !line.starts_with("import ") {
                bundle.push_str("  ");
                bundle.push_str(line);
                bundle.push('\n');
            }
        }
        bundle.push_str("})();\n\n");
    }

    // Entry module directly
    if let Some(entry_js) = sorted_modules
        .iter()
        .find(|(n, _)| *n == entry_stem)
        .map(|(_, js)| js.clone())
        .or_else(|| {
            let source = std::fs::read_to_string(entry_path).ok()?;
            let module = pyths_parser::parse(&source).ok()?;
            Some(pyths_codegen_js::codegen_inline(&module))
        })
    {
        bundle.push_str("// --- Entry ---\n");
        for line in entry_js.lines() {
            // Strip import statements in bundle mode
            if !line.starts_with("import ") {
                bundle.push_str(line);
                bundle.push('\n');
            }
        }
    }

    // Minify if requested (basic: strip comments and collapse whitespace)
    if minify {
        bundle = basic_minify(&bundle);
    }

    // Write output
    let output_path = output.map(|s| s.to_string()).unwrap_or_else(|| {
        let stem = entry_path.file_stem().unwrap().to_string_lossy();
        format!("{}.bundle.js", stem)
    });

    std::fs::write(&output_path, &bundle)?;
    if verbosity != Verbosity::Quiet {
        output::success(&format!(
            "Bundle written to {} ({} bytes)",
            output_path,
            bundle.len()
        ));
    }

    Ok(())
}

/// Basic minification: remove comments, collapse blank lines
fn basic_minify(source: &str) -> String {
    let mut result = String::new();
    let mut prev_blank = false;
    // Whether the start of the current line is inside a `...` template literal.
    // Its continuation lines are string data, so `//`-leading lines (e.g. a URL)
    // must not be dropped as comments (issue #193). Nested `${` templates are a
    // known limitation of this parity heuristic.
    let mut in_template = false;

    for line in source.lines() {
        if in_template {
            result.push_str(line);
            result.push('\n');
            if count_unescaped_backticks(line) % 2 == 1 {
                in_template = false;
            }
            prev_blank = false;
            continue;
        }

        let trimmed = line.trim();

        // Skip comment-only lines
        if trimmed.starts_with("//") {
            continue;
        }

        // Skip excessive blank lines
        if trimmed.is_empty() {
            if prev_blank {
                continue;
            }
            prev_blank = true;
        } else {
            prev_blank = false;
        }

        // Remove inline trailing comments (simple heuristic, not in strings)
        let line_no_comment = if let Some(idx) = trimmed.find("//") {
            // Don't remove if inside a string (basic check)
            let before = &trimmed[..idx];
            if before.matches('"').count() % 2 == 0
                && before.matches('\'').count() % 2 == 0
                && before.matches('`').count() % 2 == 0
            {
                trimmed[..idx].trim_end()
            } else {
                trimmed
            }
        } else {
            trimmed
        };

        if !line_no_comment.is_empty() {
            result.push_str(line_no_comment);
            result.push('\n');
        }

        // If this line opened an unterminated template literal, following lines
        // are string data.
        if count_unescaped_backticks(line_no_comment) % 2 == 1 {
            in_template = true;
        }
    }

    result
}

/// Count backticks not preceded by a backslash.
fn count_unescaped_backticks(s: &str) -> usize {
    let bytes = s.as_bytes();
    let (mut n, mut i) = (0usize, 0usize);
    while i < bytes.len() {
        match bytes[i] {
            b'\\' => {
                i += 2;
                continue;
            }
            b'`' => n += 1,
            _ => {}
        }
        i += 1;
    }
    n
}

#[cfg(test)]
mod tests {
    use super::basic_minify;

    // Issue #193 (related): a `//`-leading continuation line inside a template
    // literal (e.g. a URL) was deleted as a comment.
    #[test]
    fn keeps_slashes_inside_template_literal() {
        let src = "const u = `\n//not-a-comment/here\n`;\n";
        let out = basic_minify(src);
        assert!(
            out.contains("//not-a-comment/here"),
            "template body dropped: {out:?}"
        );
    }

    #[test]
    fn still_strips_real_comment_lines() {
        let src = "// header\nconst x = 1;\n";
        let out = basic_minify(src);
        assert!(!out.contains("// header"));
        assert!(out.contains("const x = 1;"));
    }
}
