use std::path::Path;
use std::time::{Duration, Instant};

use super::cache;
use super::output::{self, Verbosity};

/// Marker embedded at the top of every generated JS / `.d.ts` sibling. A later
/// compile recognizes its own output by this marker and safely overwrites it,
/// while a hand-written file that lacks the marker is protected (A8).
const GENERATED_MARKER: &str = "@generated by PythScribe";

/// The header line prepended to generated `.js` / `.d.ts` output.
fn generated_header() -> String {
    format!(
        "// {} — do not edit; regenerate with `pyths compile`.\n",
        GENERATED_MARKER
    )
}

/// Heuristic: does this file content look like PythScribe-generated output?
/// True iff the generated marker appears near the top.
fn looks_pyths_generated(bytes: &[u8]) -> bool {
    let head_len = bytes.len().min(512);
    String::from_utf8_lossy(&bytes[..head_len]).contains(GENERATED_MARKER)
}

/// Prepend one empty generated line to a source map's `mappings` field (a
/// leading `;`) so mapped frames still resolve after a single header line was
/// prepended to the `.js`. Returns the original string unchanged if the field
/// can't be located (defensive — better an unshifted map than a corrupted one).
fn shift_sourcemap_one_line(map_json: &str) -> String {
    let needle = "\"mappings\":";
    if let Some(i) = map_json.find(needle) {
        let after = &map_json[i + needle.len()..];
        let trimmed = after.trim_start();
        let ws = after.len() - trimmed.len();
        if trimmed.starts_with('"') {
            let insert_at = i + needle.len() + ws + 1; // just past the opening quote
            let mut out = String::with_capacity(map_json.len() + 1);
            out.push_str(&map_json[..insert_at]);
            out.push(';');
            out.push_str(&map_json[insert_at..]);
            return out;
        }
    }
    map_json.to_string()
}

/// A16: build the `deno.json` scaffold for the `deno` target. The entry
/// filename is derived from the user's `-o`, so it can contain a space or a
/// `"`. Building the JSON via `serde_json` guarantees the value is escaped and
/// the emitted `deno.json` is always valid JSON (a hand-rolled `format!` with
/// the raw filename could break the string or splice into the task command).
///
/// NOTE (follow-up): the task runs `deno run --allow-read <entry>`. The blanket
/// `--allow-read` is broad for a scaffold; tightening it to the emitted file
/// set (and quoting the entry for the task shell when it contains spaces) is a
/// tracked hardening enhancement, not done here.
fn build_deno_json(entry_basename: &str) -> String {
    let value = serde_json::json!({
        "tasks": {
            "start": format!("deno run --allow-read {}", entry_basename)
        }
    });
    format!(
        "{}\n",
        serde_json::to_string_pretty(&value).expect("serialize deno.json")
    )
}

/// A8: write a compiler-generated sibling next to the user's source safely.
///
/// Two harms are closed:
///   1. **Symlink-following.** `std::fs::write` follows symlinks, so a hostile
///      `app.js` → `~/.ssh/authorized_keys` would have the compiler overwrite
///      the link target. We `symlink_metadata` first and REFUSE to write
///      through a symlink.
///   2. **Clobbering a hand-written file.** A project with `Counter.ps` AND a
///      hand-written `Counter.js` would silently lose `Counter.js` every build
///      (and the Vite/Next plugins then `unlinkSync` it). When `marker_aware`,
///      an existing non-symlink file is overwritten only if it already carries
///      the generated marker (it is ours) or `--force` is set; otherwise we
///      refuse with a clear diagnostic.
///
/// `.js.map` (JSON — cannot carry a `//` marker) passes `marker_aware = false`
/// and is guarded by symlink-refusal only; it is always compiler-generated and
/// its sibling `.js` write (which precedes it) is itself marker-gated.
fn write_generated_sibling(
    target: &Path,
    contents: &[u8],
    marker_aware: bool,
    force: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    // If nothing exists at the path (`Err`), it is safe to create.
    if let Ok(meta) = std::fs::symlink_metadata(target) {
        let ft = meta.file_type();
        if ft.is_symlink() {
            return Err(format!(
                "refusing to write generated output through a symlink:\n    {}\n  \
                 this path is a symbolic link; writing would modify its target instead of \
                 creating a compiled sibling.\n  \
                 Remove the link or choose a different output path (-o).",
                target.display()
            )
            .into());
        }
        if marker_aware && ft.is_file() && !force {
            let is_ours = std::fs::read(target)
                .ok()
                .map(|b| looks_pyths_generated(&b))
                .unwrap_or(false);
            if !is_ours {
                return Err(format!(
                    "refusing to overwrite a file PythScribe did not generate:\n    {}\n  \
                     it lacks the `{}` marker, so it looks hand-written and would be lost.\n  \
                     Move it aside, choose a different output path (-o), or pass --force.",
                    target.display(),
                    GENERATED_MARKER
                )
                .into());
            }
        }
    }
    std::fs::write(target, contents)?;
    Ok(())
}

/// Drain the JS codegen depth-overflow marker and, if set, render a clean
/// compile-time diagnostic. `emit_expr` records the marker (and emits a
/// runtime-throwing placeholder) instead of overflowing the native stack when
/// an expression nests deeper than `MAX_EMIT_DEPTH`; this converts that marker
/// into a rendered error so the compilation fails cleanly (non-zero exit)
/// rather than shipping a booby-trapped module.
fn codegen_depth_error(source: &str, filename: &str) -> Option<Box<dyn std::error::Error>> {
    let offset = pyths_codegen_js::take_emit_overflow()?;
    let diag = pyths_diagnostic::errors::Diagnostic::error(
        format!(
            "expression nested too deeply to compile (exceeds the maximum of {} levels)",
            pyths_codegen_js::MAX_EMIT_DEPTH
        ),
        pyths_syntax::span::Span::new(offset, offset),
    )
    .with_note(
        "simplify or split the deeply-nested expression — this limit guards against \
         stack exhaustion on pathological input",
    );
    let rendered = pyths_diagnostic::render::render_diagnostics(source, filename, &[diag]);
    Some(rendered.into())
}

/// #98: create the parent directory of an output path if it's missing, with
/// a clear error naming the directory (instead of the raw
/// "The system cannot find the path specified. (os error 3)").
fn ensure_parent_dir(out_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(parent) = out_path.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            std::fs::create_dir_all(parent).map_err(|e| {
                format!(
                    "could not create output directory {}: {}",
                    parent.display(),
                    e
                )
            })?;
        }
    }
    Ok(())
}

/// Returns `true` if the file should be passed through the `.psc` expander
/// before parsing, given the resolved mode and file extension.
fn should_expand(mode: pyths_config::ExpandMode, path: &Path) -> bool {
    match mode {
        pyths_config::ExpandMode::Always => true,
        pyths_config::ExpandMode::Never => false,
        pyths_config::ExpandMode::Auto => path
            .extension()
            .and_then(|s| s.to_str())
            .map(|ext| ext.eq_ignore_ascii_case("psc"))
            .unwrap_or(false),
    }
}

/// Step 9 (--watch enhancement): polling-based file watcher that recompiles
/// `file` whenever its mtime changes. Avoids pulling in the `notify` crate
/// for the simplest possible implementation. Cache makes no-op rebuilds
/// near-instant.
///
/// Exits on Ctrl+C (signal handling left to the OS / shell).
#[allow(clippy::too_many_arguments)]
pub fn watch(
    file: &str,
    output_path_arg: Option<&str>,
    sourcemap: bool,
    no_sources_content: bool,
    timings: bool,
    dts: bool,
    target: &str,
    expand_mode: Option<pyths_config::ExpandMode>,
    react_refresh: bool,
    force: bool,
    verbosity: Verbosity,
) -> Result<(), Box<dyn std::error::Error>> {
    let path = Path::new(file);
    if !path.exists() {
        return Err(format!("File not found: {}", file).into());
    }
    if verbosity != Verbosity::Quiet {
        output::success(&format!("Watching {} (Ctrl+C to exit)", file));
    }

    // Initial compile.
    let _ = run(
        file,
        output_path_arg,
        false,
        sourcemap,
        no_sources_content,
        timings,
        dts,
        target,
        expand_mode,
        react_refresh,
        false,
        force,
        verbosity,
    );

    let mut last_mtime = std::fs::metadata(path).and_then(|m| m.modified()).ok();

    loop {
        std::thread::sleep(Duration::from_millis(200));
        let cur_mtime = match std::fs::metadata(path).and_then(|m| m.modified()) {
            Ok(m) => Some(m),
            Err(_) => continue,
        };
        if cur_mtime != last_mtime {
            last_mtime = cur_mtime;
            if verbosity != Verbosity::Quiet {
                eprintln!("--- change detected, recompiling ---");
            }
            // Run again. Errors print themselves; we keep watching.
            if let Err(e) = run(
                file,
                output_path_arg,
                false,
                sourcemap,
                no_sources_content,
                timings,
                dts,
                target,
                expand_mode,
                react_refresh,
                false,
                force,
                verbosity,
            ) {
                output::error_summary(&format!("Error: {}", e));
            }
        }
    }
}

#[allow(clippy::too_many_arguments)]
pub fn run(
    file: &str,
    output_path_arg: Option<&str>,
    stdout: bool,
    sourcemap: bool,
    no_sources_content: bool,
    timings: bool,
    dts: bool,
    target: &str,
    expand_mode: Option<pyths_config::ExpandMode>,
    react_refresh: bool,
    emit_cert: bool,
    force: bool,
    verbosity: Verbosity,
) -> Result<(), Box<dyn std::error::Error>> {
    if emit_cert && (sourcemap || stdout) {
        return Err("--emit-cert does not support --sourcemap/--stdout".into());
    }
    if emit_cert && !matches!(target, "js" | "js+wasm" | "wasm") {
        return Err("--emit-cert supports --target js (subscript-routing) and js+wasm / wasm (WASM-admission) only".into());
    }
    let path = Path::new(file);
    if !path.exists() {
        return Err(format!("File not found: {}", file).into());
    }

    let show_timings = timings || verbosity == Verbosity::Verbose;

    let t_read = Instant::now();
    let raw_source = std::fs::read_to_string(path)?;
    let d_read = t_read.elapsed();

    // Phase 2: `.psc` expansion. Resolve effective mode from CLI flag,
    // pyths.toml, then default. Mode `Auto` checks the file extension;
    // `Always` expands unconditionally; `Never` short-circuits.
    let config = pyths_config::load_or_default();
    let mode = expand_mode.unwrap_or(config.expand.mode);
    let t_expand = Instant::now();
    let source = if should_expand(mode, path) {
        // Thread both the $NAME dictionary and the %NAME idiom map through.
        pyths_expand::expand_with_config(
            &raw_source,
            &config.expand.dictionary,
            &config.expand.idioms,
        )
    } else {
        raw_source
    };
    let d_expand = t_expand.elapsed();
    let source_len = source.len();

    // Step 9: incremental cache lookup. If the source + target + compiler
    // version have already produced an output that's still on disk with the
    // recorded hash, we skip the whole pipeline. The cache only tracks single
    // JS outputs — multi-file targets (js+wasm and edge targets that emit
    // worker.js + worker.wasm + scaffolds) skip the cache entirely.
    let cache_disabled =
        std::env::var("PYTHS_NO_CACHE").is_ok() || stdout || sourcemap || dts || target != "js";
    let cache_dir = cache::cache_dir_for(path);
    let project_root = cache::project_root_for(path);
    let cache_key_value = cache::cache_key(&source, target);
    if !cache_disabled {
        // A3: the lookup re-validates the source content and confines the
        // record's output_path to the project root, so a hostile/out-of-tree
        // record is never trusted here.
        if let Some(rec) = cache::cache_lookup(&cache_dir, cache_key_value, &project_root, &source)
        {
            // The cached output is fresh. Determine where the user expects it
            // and copy if the dest is a genuinely different file from the
            // cached path.
            let want = output_path_arg.map(|s| s.to_string()).unwrap_or_else(|| {
                let stem = path.file_stem().unwrap().to_string_lossy();
                let parent = path.parent().unwrap_or(Path::new("."));
                parent
                    .join(format!("{}.js", stem))
                    .to_string_lossy()
                    .to_string()
            });
            // Compare by canonical path, not string, so we never `fs::copy` a
            // file onto itself (which would truncate it).
            let same_file = std::fs::canonicalize(&rec.output_path)
                .ok()
                .and_then(|src| {
                    std::fs::canonicalize(Path::new(&want))
                        .ok()
                        .map(|dst| src == dst)
                })
                .unwrap_or(false);
            if !same_file {
                // #98: create missing output parent dirs (`-o dist/app.js`
                // with no dist/ previously died with a raw os error 3).
                ensure_parent_dir(Path::new(&want))?;
                // A8: route the cached copy through the safe writer so the
                // destination is symlink-refused and a hand-written file is not
                // clobbered (the cached bytes already carry the marker).
                let cached_bytes = std::fs::read(&rec.output_path)?;
                write_generated_sibling(Path::new(&want), &cached_bytes, true, force)?;
            }
            if verbosity != Verbosity::Quiet {
                output::success(&format!(
                    "Cache hit: {} (skipped recompile, copied to {})",
                    rec.output_path, want
                ));
            }
            return Ok(());
        }
    }

    let filename = path.file_name().unwrap().to_string_lossy();

    // Parse
    let t_parse = Instant::now();
    let module = pyths_parser::parse(&source).map_err(|errors| {
        let diags: Vec<_> = errors
            .iter()
            .map(|e| {
                let mut diag = pyths_diagnostic::errors::Diagnostic::error(
                    &e.message,
                    pyths_syntax::span::Span::new(e.span.start, e.span.end),
                );
                for note in &e.notes {
                    diag = diag.with_note(note);
                }
                diag
            })
            .collect();

        pyths_diagnostic::render::render_diagnostics(&source, &filename, &diags)
    })?;
    let d_parse = t_parse.elapsed();

    let line_count = source.lines().count();

    // Determine output path
    let output_path = if let Some(out) = output_path_arg {
        out.to_string()
    } else {
        let stem = path.file_stem().unwrap().to_string_lossy();
        let parent = path.parent().unwrap_or(Path::new("."));
        parent
            .join(format!("{}.js", stem))
            .to_string_lossy()
            .to_string()
    };

    // Derive output stem and directory from output_path (used for .wasm, .glue.js, etc.)
    let out_path = Path::new(&output_path);
    let out_stem = out_path.file_stem().unwrap().to_string_lossy().to_string();
    let out_dir = out_path.parent().unwrap_or(Path::new("."));

    // #98: `pyths compile app.ps -o dist/app.js` with no dist/ previously
    // failed with a raw `os error 3` from fs::write. Create the missing
    // parent directories up front (every subsequent write — .js, .wasm,
    // .glue.js, .map, .d.ts — lands inside out_dir).
    ensure_parent_dir(out_path)?;

    // Edge / server targets all require WASM compilation. Each implies a
    // different bridge variant + auxiliary file layout.
    let is_edge_target = matches!(target, "wasm-edge" | "wasi" | "deno");
    let needs_wasm = matches!(target, "wasm" | "js+wasm") || is_edge_target;
    let target_only_wasm = target == "wasm";

    // === WASM compilation ===
    let wasm_output: Option<pyths_codegen_wasm::WasmCodegenOutput> = if needs_wasm {
        let t_wasm = Instant::now();
        let wasm_output = pyths_codegen_wasm::codegen_wasm(&module);
        let d_wasm = t_wasm.elapsed();

        if wasm_output.wasm.is_empty() {
            if is_edge_target {
                return Err(format!(
                    "--target {} requires at least one WASM-eligible function in the source.",
                    target
                )
                .into());
            }
            if verbosity != Verbosity::Quiet {
                output::warning_summary("No WASM-eligible functions found");
                if verbosity == Verbosity::Verbose {
                    for (name, reason) in &wasm_output.rejected_functions {
                        output::info(&format!("  Skipped {}: {}", name, reason), verbosity);
                    }
                }
            }
        }

        if !wasm_output.wasm.is_empty() {
            let wasm_path = out_dir
                .join(format!("{}.wasm", out_stem))
                .to_string_lossy()
                .to_string();

            let t_write_wasm = Instant::now();
            // A8: symlink-refusal (binary output — no marker to check).
            write_generated_sibling(Path::new(&wasm_path), &wasm_output.wasm, false, force)?;
            let d_write_wasm = t_write_wasm.elapsed();

            // Credible compilation: WASM auto-routing ADMISSION certificate.
            // Independently re-derives the FULL admission verdict (boundary +
            // body-fragment membership) from the module and cross-checks the
            // emitted `.wasm` (every admitted boundary type is WASM-representable
            // + lowerable; exports match the admitted set). It does NOT certify
            // body VALUE-equivalence (the CRIT-A6 classes) — that stays with the
            // differential + Livermore layers; see cert.rs's module header. A
            // rejected certificate fails THIS compilation.
            if emit_cert {
                let cert = pyths_codegen_wasm::cert::build_certificate(&module);
                let violations =
                    pyths_codegen_wasm::cert::check_certificate(&cert, &wasm_output.wasm, &module);
                if !violations.is_empty() {
                    for v in &violations {
                        eprintln!("error: WASM-admission certificate violation: {}", v);
                    }
                    return Err(format!(
                            "WASM-admission certificate REJECTED ({} violation(s)) — compilation discarded",
                            violations.len()
                        )
                        .into());
                }
                let cert_path = format!("{}.wasm.cert.json", output_path);
                write_generated_sibling(
                    Path::new(&cert_path),
                    cert.to_json().as_bytes(),
                    false,
                    force,
                )?;
                if verbosity != Verbosity::Quiet {
                    output::success(&format!(
                        "Certificate ACCEPTED → {} (WASM-admission)",
                        cert_path
                    ));
                }
            }

            if verbosity != Verbosity::Quiet {
                output::success(&format!(
                    "Compiled {} → {} ({} functions)",
                    file,
                    wasm_path,
                    wasm_output.compiled_functions.len()
                ));
            }

            if verbosity == Verbosity::Verbose {
                for name in &wasm_output.compiled_functions {
                    output::info(&format!("  WASM: {}", name), verbosity);
                }
                for (name, reason) in &wasm_output.rejected_functions {
                    output::info(&format!("  Skipped {}: {}", name, reason), verbosity);
                }
            }

            if show_timings {
                eprintln!("  WASM Codegen: {:.2}ms", d_wasm.as_secs_f64() * 1000.0);
                eprintln!(
                    "  WASM Write:   {:.2}ms",
                    d_write_wasm.as_secs_f64() * 1000.0
                );
            }

            // Generate glue.js for js+wasm mode (browser target)
            if target == "js+wasm" {
                // #358: compile the eligible functions ONCE MORE through the
                // plain JS backend — the exact, arbitrary-precision twins.
                // The glue embeds them and re-runs any call whose WASM
                // result would exceed i64 (`__ovf` flag / boundary guard),
                // so the fast path can never return a silently wrapped int.
                let twin_js: Option<String> = {
                    let twin_body: Vec<pyths_syntax::ast::Stmt> = module
                        .body
                        .iter()
                        .filter(|s| {
                            matches!(
                                &s.kind,
                                pyths_syntax::ast::StmtKind::FuncDef { name, .. }
                                    if wasm_output.compiled_functions.contains(name)
                            )
                        })
                        .cloned()
                        .collect();
                    if twin_body.is_empty() {
                        None
                    } else {
                        let twin_module = pyths_syntax::ast::Module {
                            body: twin_body,
                            span: module.span,
                        };
                        let twin_opts = pyths_codegen_js::CodegenOptions {
                            npm_imports: Some(&config.npm.imports),
                            ..Default::default()
                        };
                        Some(pyths_codegen_js::codegen_with_options(
                            &twin_module,
                            &twin_opts,
                        ))
                    }
                };
                let glue_js = pyths_codegen_wasm::generate_bridge_js(
                    &wasm_output,
                    &format!("./{}.wasm", out_stem),
                    twin_js.as_deref(),
                );
                let glue_path = out_dir.join(format!("{}.glue.js", out_stem));
                write_generated_sibling(&glue_path, glue_js.as_bytes(), false, force)?;
                if verbosity != Verbosity::Quiet {
                    output::success(&format!("Generated {}", glue_path.to_string_lossy()));
                }
            }

            // Edge / server targets — write self-contained module + scaffold
            if is_edge_target {
                use pyths_codegen_wasm::bridge::{append_workers_fetch_handler, BridgeTarget};
                let bridge_target = match target {
                    "wasm-edge" => BridgeTarget::CloudflareWorkers,
                    "wasi" => BridgeTarget::Wasi,
                    "deno" => BridgeTarget::Deno,
                    _ => unreachable!(),
                };
                let mut glue_js = pyths_codegen_wasm::generate_bridge_for_target(
                    bridge_target,
                    &format!("./{}.wasm", out_stem),
                    &wasm_output,
                );

                // Pick scaffold files (configs) per target; entry filename
                // follows the user's -o (or compile.rs's default).
                let scaffold_files: Vec<(String, String)> = match target {
                    "wasm-edge" => {
                        append_workers_fetch_handler(&mut glue_js, &wasm_output.export_info);
                        let entry_basename = out_path
                            .file_name()
                            .map(|s| s.to_string_lossy().to_string())
                            .unwrap_or_else(|| "worker.js".to_string());
                        let wrangler = format!(
                            "name = \"{}\"\nmain = \"./{}\"\ncompatibility_date = \"2024-09-25\"\n",
                            out_stem, entry_basename
                        );
                        let pkg = "{\n  \"private\": true,\n  \"type\": \"module\",\n  \"devDependencies\": {\n    \"wrangler\": \"^3\"\n  }\n}\n".to_string();
                        vec![
                            ("wrangler.toml".to_string(), wrangler),
                            ("package.json".to_string(), pkg),
                        ]
                    }
                    "wasi" => vec![],
                    "deno" => {
                        let entry_basename = out_path
                            .file_name()
                            .map(|s| s.to_string_lossy().to_string())
                            .unwrap_or_else(|| "main.ts".to_string());
                        // A16 hardening: build the JSON via serde_json (see
                        // `build_deno_json`) so a `"` or space in the output
                        // name cannot break the JSON string.
                        let deno_json = build_deno_json(&entry_basename);
                        vec![("deno.json".to_string(), deno_json)]
                    }
                    _ => unreachable!(),
                };

                // Write the entry file at the user-specified output_path.
                write_generated_sibling(Path::new(&output_path), glue_js.as_bytes(), false, force)?;
                if verbosity != Verbosity::Quiet {
                    output::success(&format!("Generated {}", output_path));
                }

                for (name, contents) in &scaffold_files {
                    let p = out_dir.join(name);
                    // Don't overwrite if the user already has a wrangler.toml etc.
                    if !p.exists() {
                        std::fs::write(&p, contents)?;
                        if verbosity != Verbosity::Quiet {
                            output::success(&format!("Generated {}", p.to_string_lossy()));
                        }
                    }
                }
            }

            // Run wasm-opt -Os (size-optimized for web) if available.
            // The reduction surfaces at normal verbosity now — users
            // benefit from seeing it without needing --verbose.
            match pyths_codegen_wasm::optimize::run_wasm_opt(&wasm_path) {
                Ok(Some(r)) => {
                    if verbosity != Verbosity::Quiet {
                        let pct = (1.0 - r.size_after as f64 / r.size_before as f64) * 100.0;
                        output::info(
                            &format!(
                                "  wasm-opt -{}: {} → {} bytes ({:.0}% reduction)",
                                r.level, r.size_before, r.size_after, pct
                            ),
                            verbosity,
                        );
                    }
                }
                Ok(None) => {
                    if verbosity == Verbosity::Verbose {
                        output::info(
                                "  wasm-opt not found on PATH — install with `npm i -g wasm-opt` for size reduction",
                                verbosity,
                            );
                    }
                }
                Err(e) => {
                    if verbosity != Verbosity::Quiet {
                        output::info(&format!("  wasm-opt error: {}", e), verbosity);
                    }
                }
            }
        }

        // If target is "wasm" only or any edge target, we're done after WASM
        if target_only_wasm || is_edge_target {
            if show_timings {
                let d_total = d_read + d_expand + d_parse + d_wasm;
                eprintln!("  Read:    {:.2}ms", d_read.as_secs_f64() * 1000.0);
                if d_expand.as_micros() > 0 {
                    eprintln!("  Expand:  {:.2}ms", d_expand.as_secs_f64() * 1000.0);
                }
                eprintln!("  Parse:   {:.2}ms", d_parse.as_secs_f64() * 1000.0);
                eprintln!(
                    "  Total:   {:.2}ms ({} lines, {:.1} KB)",
                    d_total.as_secs_f64() * 1000.0,
                    line_count,
                    source_len as f64 / 1024.0,
                );
            }
            return Ok(());
        }

        Some(wasm_output)
    } else {
        None
    };

    // === JS compilation ===
    if sourcemap && !stdout {
        // Compile with source map
        // Note: sourcemap mode does not currently integrate wasm_skip (bridge re-exports
        // are appended separately if needed in a future enhancement).
        let map_path = format!("{}.map", output_path);
        let t_codegen = Instant::now();
        let result = pyths_codegen_js::codegen_with_sourcemap_and_options(
            &module,
            &source,
            &filename,
            &output_path,
            &config.npm.imports,
            target == "worker",
            no_sources_content,
        );
        let d_codegen = t_codegen.elapsed();

        if let Some(err) = codegen_depth_error(&source, &filename) {
            return Err(err);
        }

        // A8: prepend the generated marker so a later compile recognizes its
        // own output. The marker line sits BEFORE the mapped code, so we also
        // pad the source map with one leading `;` (below) to keep line numbers
        // aligned. Placing it here (not appended) keeps `//# sourceMappingURL`
        // last.
        let header = generated_header();
        let js_with_ref = format!(
            "{}{}\n//# sourceMappingURL={}\n",
            header,
            result.js,
            Path::new(&map_path).file_name().unwrap().to_string_lossy()
        );

        let t_write = Instant::now();
        // A8: symlink-refusal + don't clobber a hand-written `.js` without --force.
        write_generated_sibling(Path::new(&output_path), js_with_ref.as_bytes(), true, force)?;
        if let Some(map) = result.source_map {
            // The marker added one line ahead of all generated code; shift the
            // VLQ mappings down by one line so frames still resolve correctly.
            let shifted = shift_sourcemap_one_line(&map);
            // `.js.map` is JSON (no marker): symlink-refusal only. Its sibling
            // `.js` write above is marker-gated, so we only reach here when that
            // write was permitted.
            write_generated_sibling(Path::new(&map_path), shifted.as_bytes(), false, force)?;
        }
        let d_write = t_write.elapsed();

        if verbosity != Verbosity::Quiet {
            output::success(&format!(
                "Compiled {} → {} (+ {})",
                file, output_path, map_path
            ));
        }

        if show_timings {
            let d_total = d_read + d_expand + d_parse + d_codegen + d_write;
            eprintln!("  Read:    {:.2}ms", d_read.as_secs_f64() * 1000.0);
            if d_expand.as_micros() > 0 {
                eprintln!("  Expand:  {:.2}ms", d_expand.as_secs_f64() * 1000.0);
            }
            eprintln!("  Parse:   {:.2}ms", d_parse.as_secs_f64() * 1000.0);
            eprintln!("  Codegen: {:.2}ms", d_codegen.as_secs_f64() * 1000.0);
            eprintln!("  Write:   {:.2}ms", d_write.as_secs_f64() * 1000.0);
            eprintln!(
                "  Total:   {:.2}ms ({} lines, {:.1} KB)",
                d_total.as_secs_f64() * 1000.0,
                line_count,
                source_len as f64 / 1024.0,
            );
        }
    } else {
        // Compile without source map
        let t_codegen = Instant::now();

        // For js+wasm with compiled functions, use bridge-aware codegen.
        // The `CodegenOptions` builder routes React-Refresh emission +
        // npm overrides + WASM bridge through one path so we don't have
        // to fan out to specific helper variants.
        let glue_filename;
        let mut opts = pyths_codegen_js::CodegenOptions {
            npm_imports: Some(&config.npm.imports),
            react_refresh,
            ..Default::default()
        };
        // --target worker: emit DOM-free runtime imports from pyths-runtime/core
        // instead of pyths-runtime. Only the import path changes; all other
        // codegen is identical. (B-030 follow-up D)
        if target == "worker" {
            opts.worker_runtime = true;
        }
        if let Some(ref wo) = wasm_output {
            if !wo.compiled_functions.is_empty() {
                glue_filename = format!("./{}.glue.js", out_stem);
                opts.wasm_skip = Some(&wo.compiled_functions);
                opts.wasm_glue_filename = Some(&glue_filename);
            }
        }
        // Credible compilation (§7.2): certified codegen returns the
        // subscript-routing certificate; the checker re-applies the
        // rules to every recorded site and cross-checks the emitted JS.
        // A rejected certificate fails THIS compilation (Axon-style
        // translation validation — validate the run, not the pass).
        let mut cert_json: Option<String> = None;
        let js = if emit_cert {
            let certified = pyths_codegen_js::codegen_certified(&module, &opts);
            let violations =
                pyths_codegen_js::cert::check_certificate(&certified.certificate, &certified.js);
            if !violations.is_empty() {
                for v in &violations {
                    eprintln!("error: certificate violation: {}", v);
                }
                return Err(format!(
                    "subscript-routing certificate REJECTED ({} violation(s)) — compilation discarded",
                    violations.len()
                )
                .into());
            }
            cert_json = Some(certified.certificate.to_json());
            certified.js
        } else {
            pyths_codegen_js::codegen_with_options(&module, &opts)
        };

        let d_codegen = t_codegen.elapsed();

        if let Some(err) = codegen_depth_error(&source, &filename) {
            return Err(err);
        }

        if stdout {
            print!("{}", js);

            if show_timings {
                let d_total = d_read + d_expand + d_parse + d_codegen;
                eprintln!("  Read:    {:.2}ms", d_read.as_secs_f64() * 1000.0);
                if d_expand.as_micros() > 0 {
                    eprintln!("  Expand:  {:.2}ms", d_expand.as_secs_f64() * 1000.0);
                }
                eprintln!("  Parse:   {:.2}ms", d_parse.as_secs_f64() * 1000.0);
                eprintln!("  Codegen: {:.2}ms", d_codegen.as_secs_f64() * 1000.0);
                eprintln!(
                    "  Total:   {:.2}ms ({} lines, {:.1} KB)",
                    d_total.as_secs_f64() * 1000.0,
                    line_count,
                    source_len as f64 / 1024.0,
                );
            }
            return Ok(());
        }

        // A8: prepend the generated marker so a later compile recognizes its
        // own output and a hand-written `.js` is protected.
        let final_js = format!("{}{}", generated_header(), js);

        let t_write = Instant::now();
        write_generated_sibling(Path::new(&output_path), final_js.as_bytes(), true, force)?;
        if let Some(json) = &cert_json {
            let cert_path = format!("{}.cert.json", output_path);
            write_generated_sibling(Path::new(&cert_path), json.as_bytes(), false, force)?;
            if verbosity != Verbosity::Quiet {
                output::success(&format!(
                    "Certificate ACCEPTED → {} (subscript-routing)",
                    cert_path
                ));
            }
        }
        let d_write = t_write.elapsed();

        // Step 9: write a cache record so subsequent compiles can skip codegen.
        if !cache_disabled {
            let record = cache::CacheRecord {
                key: cache_key_value,
                source: file.to_string(),
                source_hash: cache::fnv1a64(source.as_bytes()),
                target: target.to_string(),
                output_path: output_path.clone(),
                // Hash the ACTUAL bytes on disk (marker included) so the
                // lookup's output re-validation matches.
                output_hash: cache::fnv1a64(final_js.as_bytes()),
                timestamp: cache::current_timestamp(),
            };
            // B15: cache-store failure must not break the compile, but a silent
            // swallow means a persistent permissions problem degrades every
            // build to a full recompile with no signal. Warn once.
            if let Err(e) = cache::cache_store(&cache_dir, &record) {
                if verbosity != Verbosity::Quiet {
                    eprintln!(
                        "warning: could not write compile cache ({}): {} — \
                         builds will not be cached (recompiling in full each time).",
                        cache_dir.display(),
                        e
                    );
                }
            }
        }

        if verbosity != Verbosity::Quiet {
            output::success(&format!("Compiled {} → {}", file, output_path));
        }

        if show_timings {
            let d_total = d_read + d_expand + d_parse + d_codegen + d_write;
            eprintln!("  Read:    {:.2}ms", d_read.as_secs_f64() * 1000.0);
            if d_expand.as_micros() > 0 {
                eprintln!("  Expand:  {:.2}ms", d_expand.as_secs_f64() * 1000.0);
            }
            eprintln!("  Parse:   {:.2}ms", d_parse.as_secs_f64() * 1000.0);
            eprintln!("  Codegen: {:.2}ms", d_codegen.as_secs_f64() * 1000.0);
            eprintln!("  Write:   {:.2}ms", d_write.as_secs_f64() * 1000.0);
            eprintln!(
                "  Total:   {:.2}ms ({} lines, {:.1} KB)",
                d_total.as_secs_f64() * 1000.0,
                line_count,
                source_len as f64 / 1024.0,
            );
        }
    }

    // Emit .d.ts if requested
    if dts && !stdout {
        let dts_path = output_path.replace(".js", ".d.ts");
        let dts_content = format!(
            "{}{}",
            generated_header(),
            pyths_codegen_js::codegen_dts(&module)
        );
        // A8: symlink-refusal + marker-gated overwrite (a `.d.ts` can carry a
        // `//` comment marker).
        write_generated_sibling(Path::new(&dts_path), dts_content.as_bytes(), true, force)?;
        if verbosity != Verbosity::Quiet {
            output::success(&format!("Emitted {}", dts_path));
        }
    }

    Ok(())
}

#[cfg(test)]
mod a8_tests {
    use super::*;
    use std::path::PathBuf;

    fn scratch(tag: &str) -> PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static N: AtomicU64 = AtomicU64::new(0);
        let id = N.fetch_add(1, Ordering::SeqCst);
        let d =
            std::env::temp_dir().join(format!("pyths_a8_{}_{}_{}", tag, std::process::id(), id));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[cfg(unix)]
    fn try_symlink(target: &Path, link: &Path) -> std::io::Result<()> {
        std::os::unix::fs::symlink(target, link)
    }
    #[cfg(windows)]
    fn try_symlink(target: &Path, link: &Path) -> std::io::Result<()> {
        std::os::windows::fs::symlink_file(target, link)
    }

    #[test]
    fn creates_a_fresh_sibling() {
        let d = scratch("fresh");
        let t = d.join("out.js");
        write_generated_sibling(&t, b"CODE", true, false).unwrap();
        assert!(t.exists());
        assert_eq!(std::fs::read(&t).unwrap(), b"CODE");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn refuses_to_clobber_handwritten_without_marker() {
        let d = scratch("handwritten");
        let t = d.join("Counter.js");
        std::fs::write(&t, b"export const mine = 1; // hand-written").unwrap();
        let err = write_generated_sibling(&t, b"GENERATED", true, false).unwrap_err();
        assert!(err.to_string().contains("did not generate"), "err: {}", err);
        // File must be untouched.
        assert_eq!(
            std::fs::read(&t).unwrap(),
            b"export const mine = 1; // hand-written"
        );
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn overwrites_own_marked_output() {
        let d = scratch("marked");
        let t = d.join("out.js");
        let marked = format!("{}old body", generated_header());
        std::fs::write(&t, marked.as_bytes()).unwrap();
        // Overwriting our own (marked) output is allowed without --force.
        write_generated_sibling(&t, b"NEWBODY", true, false).unwrap();
        assert_eq!(std::fs::read(&t).unwrap(), b"NEWBODY");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn force_overwrites_handwritten() {
        let d = scratch("force");
        let t = d.join("out.js");
        std::fs::write(&t, b"hand-written").unwrap();
        write_generated_sibling(&t, b"NEW", true, true).unwrap();
        assert_eq!(std::fs::read(&t).unwrap(), b"NEW");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn refuses_to_write_through_a_symlink() {
        let d = scratch("symlink");
        let victim = d.join("victim.txt");
        std::fs::write(&victim, b"ORIGINAL-SECRET").unwrap();
        let link = d.join("app.js");
        // Creating a symlink may require privilege (Windows without dev mode).
        // Skip the assertion if the OS denies it — the logic is still covered
        // on platforms where symlink creation succeeds (unix/CI).
        if try_symlink(&victim, &link).is_err() {
            eprintln!("skipping symlink test: OS denied symlink creation");
            let _ = std::fs::remove_dir_all(&d);
            return;
        }
        let err = write_generated_sibling(&link, b"PWNED", true, false).unwrap_err();
        assert!(err.to_string().contains("symlink"), "err: {}", err);
        // The symlink target must be untouched — we did NOT follow the link.
        assert_eq!(std::fs::read(&victim).unwrap(), b"ORIGINAL-SECRET");
        // Even --force must not write through a symlink.
        let err2 = write_generated_sibling(&link, b"PWNED", true, true).unwrap_err();
        assert!(err2.to_string().contains("symlink"), "err2: {}", err2);
        assert_eq!(std::fs::read(&victim).unwrap(), b"ORIGINAL-SECRET");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn sourcemap_shift_prepends_one_semicolon() {
        let map = r#"{"version":3,"sources":["a.ps"],"mappings":"AAAA,CAAC"}"#;
        let shifted = shift_sourcemap_one_line(map);
        assert!(
            shifted.contains(r#""mappings":";AAAA,CAAC""#),
            "got: {}",
            shifted
        );
    }

    #[test]
    fn deno_json_is_valid_for_normal_name() {
        let json = build_deno_json("main.ts");
        let v: serde_json::Value = serde_json::from_str(&json).expect("valid JSON");
        assert_eq!(v["tasks"]["start"], "deno run --allow-read main.ts");
    }

    #[test]
    fn deno_json_escapes_space_and_quote_in_name() {
        // A16: an output name with a space or a `"` must still yield valid JSON
        // (previously a raw format! would break the string / splice the task).
        for name in ["my app.ts", "we\"ird.ts", "a\\b.ts"] {
            let json = build_deno_json(name);
            let v: serde_json::Value = serde_json::from_str(&json)
                .unwrap_or_else(|e| panic!("invalid JSON for {name:?}: {e}\n{json}"));
            assert_eq!(
                v["tasks"]["start"],
                serde_json::Value::String(format!("deno run --allow-read {name}")),
                "task value round-trips for {name:?}"
            );
        }
    }
}
