//! safewrite.rs — THE one canonical safe-write API for every generated output.
//!
//! Rounds 1–3 of the 2026-08 security campaign patched generated-output
//! writing per call site (js, dts, map, wasm, glue, cert, edge entry,
//! scaffolds), and each site re-derived its own inspection, ownership, and
//! ordering logic — which is exactly how the residual TOCTOU / platform
//! defects survived three review rounds. Round 4 closes the CLASS instead:
//! this module is the single place that knows how to write a generated
//! output, and `compile.rs` / `bundle.rs` only *declare* what they intend to
//! write.
//!
//! ## The model
//!
//! 1. **Declare the complete output graph.** A command builds a
//!    `Vec<PlannedOutput>` — every destination it could touch — and calls
//!    [`OutputPlan::preflight`] ONCE before any write (P10). Preflight applies
//!    the SAME checks the final writer applies (symlink, non-regular file,
//!    hard-link count, ownership) plus destination-ALIAS detection (two
//!    planned outputs resolving to one file, e.g. `--target deno -o
//!    worker.wasm`), so no refusal the preflight can detect surfaces after a
//!    partial write. Honest scope: this REDUCES partial-artifact risk, it
//!    does not eliminate it — writes are sequential, so a mid-sequence
//!    failure (ENOSPC, or a destination appearing between preflight and its
//!    exclusive create) still leaves the outputs written before it; a
//!    partial artifact is later rebuilt (marker intact) or refused with an
//!    explicit error, never silently trusted.
//!
//! 2. **Ownership is proven on the artifact itself, on the writing fd.**
//!    * Text outputs carry the leading `// @generated by PythScribe` marker.
//!    * `.wasm` outputs carry a `pythscribe.generated` WASM custom section
//!      (see `pyths_codegen_wasm::optimize`) — so the tool's OWN rebuild
//!      succeeds without `--force`, while a truly-unowned `.wasm` is refused.
//!    * Marker-less sidecars (`.map`, `.cert.json`) are overwritable only if
//!      the SIDECAR ITSELF is absent, or its primary EXISTS AND IS OWNED —
//!      a fresh (absent) primary never authorizes destroying an unowned
//!      sidecar. Because a sidecar cannot prove ownership on the fd, the
//!      writer proves content identity instead: the fd's content must be
//!      byte-identical to what preflight authorized (same for `--force`).
//!      There is no proof-free overwrite path.
//!    * Round-6: on top of the evidence, EVERY overwrite is bound to the
//!      FILE IDENTITY (dev+inode / volume+file-index) captured at preflight
//!      from the same handle that read the evidence, and re-verified on the
//!      writing fd. Evidence alone is forgeable by construction (see the
//!      trust-model section below); the identity is what refuses a
//!      DIFFERENT, genuinely-marked file renamed over the destination after
//!      preflight. `rewrite` (wasm-opt placement) is likewise bound to the
//!      identity of the file this same invocation wrote.
//!
//! 3. **One fd-verified writer.** Overwrites open WITHOUT truncate
//!    (`libc::O_NOFOLLOW` on unix — the per-arch-correct constant; a
//!    hardcoded value was wrong on aarch64-linux, a released target), fstat
//!    the fd (regular file, link count EXACTLY 1 — 0 means the destination
//!    was unlinked after our open and this is an orphan; enforced on unix
//!    via fstat and on Windows via `GetFileInformationByHandle` on the same
//!    handle), verify the ownership/identity proof ON THAT SAME fd, and only
//!    then `set_len(0)` + `write_all` on the same handle. Fresh creations
//!    are `O_EXCL`.
//!
//! ## What the ownership marker is — and is NOT
//!
//! The marker (text header / wasm custom section) is **accident
//! prevention**: it stops the compiler from clobbering a file a HUMAN put
//! there — a hand-written `Counter.js`, a foreign `.wasm`, a stale artifact
//! from another tool. It is **not a security boundary against a malicious
//! local process**: anyone who can write to the build directory can also
//! paste the `@generated` line or append the custom section and "forge"
//! ownership — and equally could have written the destination directly.
//! Defending files from an attacker who already has write access to the same
//! directory is out of scope for any marker scheme; that case belongs to
//! filesystem permissions and the OS trust boundary (see docs/security.md
//! §1/§6). The fd-verified writer's job is narrower and real: no-follow
//! opens on POSIX (`O_NOFOLLOW`; Windows has no such flag — the pre-open
//! `symlink_metadata` check plus privilege-gated symlink creation is the
//! documented residual there, e.g. a link to a saved copy of the SAME file
//! swapped in after preflight passes identity+evidence and the write
//! follows it), never truncate before the identity+ownership proof, never
//! write what preflight did not authorize.
//!
//! ## Documented residuals (platform)
//!
//! * **Windows** has no `O_NOFOLLOW`; the overwrite path relies on the
//!   pre-open `symlink_metadata` plus the fd proof. Symlink creation there
//!   is privilege-gated (admin / developer mode), so the exposure is
//!   accepted and documented rather than claimed closed.
//! * **Case-folding** in alias detection covers Windows and macOS defaults;
//!   a case-insensitive mount on Linux (or a case-sensitive APFS volume) is
//!   not modeled — the exclusive-create/fd checks still fail closed on the
//!   real collision, only later.

use std::collections::HashMap;
use std::io::{Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};

type BoxError = Box<dyn std::error::Error>;

/// Marker embedded at the top of every generated text output. A later
/// compile recognizes its own output by this marker and safely overwrites it,
/// while a hand-written file that lacks the marker is protected (A8).
pub const GENERATED_MARKER: &str = "@generated by PythScribe";

/// The header line prepended to generated `.js` / `.d.ts` / glue output.
pub(crate) fn generated_header() -> String {
    format!(
        "// {} — do not edit; regenerate with `pyths compile`.\n",
        GENERATED_MARKER
    )
}

/// Does this file content look like PythScribe-generated output? P4: the marker
/// must be the LEADING `//` comment, not a substring anywhere in the first 512
/// bytes — a hand-written file that merely mentions "@generated by PythScribe"
/// (e.g. in a doc comment) must NOT be treated as owned and overwritten.
pub(crate) fn looks_pyths_generated(bytes: &[u8]) -> bool {
    let head_len = bytes.len().min(512);
    let head = String::from_utf8_lossy(&bytes[..head_len]);
    head.trim_start()
        .starts_with(&format!("// {}", GENERATED_MARKER))
}

/// What kind of generated output a destination is — this decides how its
/// ownership is proven.
#[derive(Clone, Debug)]
pub enum OutputKind {
    /// `.js` / `.d.ts` / `.glue.js` / edge entry / bundle — owned via the
    /// leading `// @generated` marker, verified on the writing fd.
    MarkedText,
    /// `.wasm` — owned via the `pythscribe.generated` custom section,
    /// verified on the writing fd.
    WasmModule,
    /// Marker-less sidecar (`.js.map`, `.cert.json`, `.wasm.cert.json`) —
    /// overwritable only when absent or when `primary` exists AND is owned.
    /// A fresh (absent) primary authorizes NOTHING.
    Sidecar { primary: PathBuf },
    /// Fixed-name scaffold config (`wrangler.toml`, `package.json`,
    /// `deno.json`): an existing regular file is KEPT (the user's config
    /// wins); symlinks — including dangling ones — are refused; creation is
    /// exclusive.
    ScaffoldIfAbsent,
}

/// One destination the current command intends to write.
pub struct PlannedOutput {
    pub path: PathBuf,
    pub kind: OutputKind,
}

impl PlannedOutput {
    pub fn marked_text(path: impl Into<PathBuf>) -> Self {
        PlannedOutput { path: path.into(), kind: OutputKind::MarkedText }
    }
    pub fn wasm(path: impl Into<PathBuf>) -> Self {
        PlannedOutput { path: path.into(), kind: OutputKind::WasmModule }
    }
    pub fn sidecar(path: impl Into<PathBuf>, primary: impl Into<PathBuf>) -> Self {
        PlannedOutput {
            path: path.into(),
            kind: OutputKind::Sidecar { primary: primary.into() },
        }
    }
    pub fn scaffold(path: impl Into<PathBuf>) -> Self {
        PlannedOutput { path: path.into(), kind: OutputKind::ScaffoldIfAbsent }
    }
}

/// Preflight decision for one destination.
#[derive(Debug)]
enum Decision {
    /// Nothing was there — create exclusively (`O_EXCL`).
    Create,
    /// An authorized file was there — fd-verified overwrite carrying the
    /// EXACT proof the writer must re-establish on the fd. There is no
    /// proof-free overwrite path (round-5 fix): even `--force` and sidecar
    /// overwrites verify, on the writing fd, that the file being truncated is
    /// byte-identical to the one preflight authorized destroying — and every
    /// proof also carries the FILE IDENTITY preflight captured, so only that
    /// very file, not a marked or byte-identical substitute, can be
    /// overwritten (round-6 fix).
    Overwrite(OverwriteProof),
    /// Existing scaffold — keep the user's file, write nothing.
    Keep,
}

/// How ownership/identity is proven ON THE WRITING FD before any truncation.
///
/// Round-6: EVERY overwrite proof carries the [`FileIdentity`] captured at
/// preflight, and the writer verifies it on the writing fd BEFORE the
/// evidence check. The evidence alone was not enough: a DIFFERENT
/// PythScribe-marked file renamed over the destination after preflight
/// carried a valid marker and was truncated. Binding the write to the exact
/// (volume, file-id) pair preflight inspected closes that substitution class
/// — only the SAME file preflight authorized destroying can be overwritten,
/// never merely "some marked file".
#[derive(Debug)]
struct OverwriteProof {
    /// The exact file preflight authorized overwriting.
    identity: FileIdentity,
    /// The ownership/content evidence re-established on the writing fd.
    evidence: Evidence,
}

#[derive(Debug)]
enum Evidence {
    /// Leading `// @generated` marker read from the fd.
    MarkerOnFd,
    /// `pythscribe.generated` WASM custom section read from the fd.
    WasmSectionOnFd,
    /// The exact bytes preflight authorized destroying (`--force`, or a
    /// marker-less sidecar whose primary is owned). The fd's current content
    /// must equal them — a same-file content change after preflight is
    /// refused (a different-file swap is already refused by the identity).
    Bytes(Vec<u8>),
}

/// A file's stable on-disk identity: `(device, inode)` on unix,
/// `(volume serial, file index)` on Windows (`GetFileInformationByHandle`
/// through the safe `winapi-util` wrapper — keeps the compiler
/// `unsafe`-free). Hard links share an identity; the exactly-1 link-count
/// check is what rules those out. What THIS rules out is substitution: a
/// different file moved over the destination after preflight has a different
/// identity, marker or no marker. (Residual, documented: a filesystem that
/// does not report stable 64-bit file IDs weakens this to the evidence
/// checks; NTFS/ext4/APFS — everything we ship to — reports them.)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct FileIdentity {
    volume: u64,
    file: u64,
}

/// Identity of an OPEN file, read from the handle itself (never a fresh
/// path lookup — the whole point is that the handle is the thing we verified
/// and will truncate). Fails CLOSED: if the identity cannot be queried, the
/// write is refused.
fn file_identity(f: &std::fs::File) -> Result<FileIdentity, BoxError> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt;
        let m = f.metadata()?;
        Ok(FileIdentity { volume: m.dev(), file: m.ino() })
    }
    #[cfg(windows)]
    {
        let info = winapi_util::file::information(f).map_err(|e| -> BoxError {
            format!(
                "refusing to write generated output: could not query the destination's \
                 file identity ({}) — cannot prove it is the file the pre-flight check \
                 authorized overwriting.",
                e
            )
            .into()
        })?;
        Ok(FileIdentity {
            volume: info.volume_serial_number(),
            file: info.file_index(),
        })
    }
    #[cfg(not(any(unix, windows)))]
    {
        let _ = f;
        // No identity primitive on this platform (none we ship to) — the
        // evidence checks still apply. Documented residual.
        Ok(FileIdentity { volume: 0, file: 0 })
    }
}

/// The preflighted output plan. Every write MUST go through [`OutputPlan::write`];
/// a path that was not preflighted is refused (fail closed) — that is the
/// mechanism that keeps future call sites from bypassing the checks.
#[derive(Debug)]
pub struct OutputPlan {
    entries: HashMap<PathBuf, (Decision, OutputKind)>,
    /// Identity of each file THIS plan wrote in THIS invocation, captured
    /// from the writing handle itself. `rewrite` verifies against it, so a
    /// re-write can only ever land on the exact file this invocation
    /// produced (round-6 fix — a marker-bearing file swapped in between
    /// `write` and `rewrite` no longer passes on its marker alone).
    written: std::sync::Mutex<HashMap<PathBuf, FileIdentity>>,
}

impl OutputPlan {
    /// Check EVERY declared destination — existence, symlink, dir-vs-file,
    /// hard-link count, ownership, and destination aliasing — BEFORE any
    /// write. Returns the plan on success; any refusal aborts the whole
    /// command with nothing written.
    pub fn preflight(outputs: &[PlannedOutput], force: bool) -> Result<OutputPlan, BoxError> {
        // Destination aliasing: two planned outputs must never resolve to the
        // same file (e.g. `--target deno -o worker.wasm` makes the WASM and
        // the entry identical; `-o app.out` makes the `.d.ts` path collide
        // with the `.js`). Both would pass individual checks as "absent" and
        // then clobber each other.
        let mut seen: HashMap<String, &Path> = HashMap::new();
        for o in outputs {
            if let Some(prev) = seen.insert(alias_key(&o.path), &o.path) {
                return Err(format!(
                    "refusing to build: two generated outputs resolve to the same \
                     destination:\n    {}\n    {}\n  \
                     Choose a different output path (-o) so every artifact has its own file.",
                    prev.display(),
                    o.path.display()
                )
                .into());
            }
        }

        let mut entries = HashMap::new();
        for o in outputs {
            let decision = decide(o, outputs, force)?;
            entries.insert(o.path.clone(), (decision, o.kind.clone()));
        }
        Ok(OutputPlan {
            entries,
            written: std::sync::Mutex::new(HashMap::new()),
        })
    }

    /// Write one preflighted destination. Returns `Ok(true)` if bytes were
    /// written, `Ok(false)` if an existing scaffold was kept.
    pub fn write(&self, path: &Path, contents: &[u8]) -> Result<bool, BoxError> {
        let (decision, kind) = self.entries.get(path).ok_or_else(|| -> BoxError {
            format!(
                "internal error: write of an unplanned output:\n    {}\n  \
                 every generated output must be declared to OutputPlan::preflight first.",
                path.display()
            )
            .into()
        })?;
        let _ = kind;
        match decision {
            Decision::Keep => Ok(false),
            Decision::Create => {
                let id = create_new_write(path, contents)?;
                self.written.lock().unwrap().insert(path.to_path_buf(), id);
                Ok(true)
            }
            Decision::Overwrite(proof) => {
                let id = overwrite_on_fd(path, contents, proof)?;
                self.written.lock().unwrap().insert(path.to_path_buf(), id);
                Ok(true)
            }
        }
    }

    /// Re-write a destination this plan already wrote in THIS invocation
    /// (wasm-opt's optimized module replacing the fresh `.wasm` we produced
    /// moments earlier). The destination must be planned AND already written
    /// by this plan; the write is fd-verified against BOTH the identity of
    /// the file our own `write` produced (captured from the writing handle —
    /// round-6 fix: a DIFFERENT marker-bearing file swapped in since our
    /// write has a different identity and is refused) and the artifact's own
    /// ownership evidence (round-5 fix: the optimized module used to be
    /// `fs::rename`d over the destination unverified).
    pub fn rewrite(&self, path: &Path, contents: &[u8]) -> Result<(), BoxError> {
        let (_, kind) = self.entries.get(path).ok_or_else(|| -> BoxError {
            format!(
                "internal error: rewrite of an unplanned output:\n    {}\n  \
                 every generated output must be declared to OutputPlan::preflight first.",
                path.display()
            )
            .into()
        })?;
        let identity = self
            .written
            .lock()
            .unwrap()
            .get(path)
            .copied()
            .ok_or_else(|| -> BoxError {
                format!(
                    "internal error: rewrite of an output this invocation has not \
                     written:\n    {}\n  \
                     rewrite may only replace an artifact this same plan produced.",
                    path.display()
                )
                .into()
            })?;
        let evidence = match kind {
            OutputKind::MarkedText => Evidence::MarkerOnFd,
            OutputKind::WasmModule => Evidence::WasmSectionOnFd,
            _ => {
                return Err(format!(
                    "internal error: rewrite is only supported for outputs that carry their \
                     own ownership proof (text marker / wasm section):\n    {}",
                    path.display()
                )
                .into())
            }
        };
        let proof = OverwriteProof { identity, evidence };
        let id = overwrite_on_fd(path, contents, &proof)?;
        self.written.lock().unwrap().insert(path.to_path_buf(), id);
        Ok(())
    }
}

/// Single-destination convenience (bundle output, cache-hit copy): preflight
/// one output and write it.
pub fn write_single(
    path: &Path,
    contents: &[u8],
    kind: OutputKind,
    force: bool,
) -> Result<bool, BoxError> {
    let planned = [PlannedOutput { path: path.to_path_buf(), kind }];
    let plan = OutputPlan::preflight(&planned, force)?;
    plan.write(path, contents)
}

// ---------------------------------------------------------------------------
// Preflight internals
// ---------------------------------------------------------------------------

/// Normalized comparison key for alias detection. Canonicalizes the file when
/// it exists, else its parent (the common case for fresh outputs), so `./a.js`
/// and `a.js` and `sub/../a.js` all collide. Case-folded on Windows.
fn alias_key(p: &Path) -> String {
    let norm = match std::fs::canonicalize(p) {
        Ok(c) => c,
        Err(_) => {
            let parent = p
                .parent()
                .filter(|q| !q.as_os_str().is_empty())
                .unwrap_or(Path::new("."));
            let base = p.file_name().map(|b| b.to_os_string()).unwrap_or_default();
            match std::fs::canonicalize(parent) {
                Ok(cp) => cp.join(base),
                Err(_) => p.to_path_buf(),
            }
        }
    };
    let s = norm.to_string_lossy().into_owned();
    // Round-5: case-fold on macOS too — default APFS/HFS+ are case-
    // insensitive, so `worker.WASM` and `worker.wasm` are ONE file there and
    // must collide in the alias check. (Residual, documented: a
    // case-insensitive mount on Linux, or a case-SENSITIVE volume on macOS,
    // is not detected — the per-destination exclusive-create/fd checks still
    // fail closed on the actual collision, just later and less tidily.)
    if cfg!(any(windows, target_os = "macos")) {
        s.to_lowercase()
    } else {
        s
    }
}

/// State of an output path after a no-follow inspection.
enum Inspection {
    Absent,
    Existing(std::fs::Metadata),
}

/// SEC #5/#10/#12: shared no-follow, fail-closed inspection for EVERY
/// destination. `symlink_metadata` sees the link itself (unlike
/// `Path::exists`, which follows and reports a DANGLING link as absent — the
/// #12 scaffold bug), so symlinks are refused here rather than followed.
/// Non-regular files are refused, and any metadata error other than "not
/// found" fails closed: if we cannot prove the destination is safe we do not
/// write it.
fn inspect(target: &Path) -> Result<Inspection, BoxError> {
    match std::fs::symlink_metadata(target) {
        Ok(meta) => {
            let ft = meta.file_type();
            if ft.is_symlink() {
                return Err(format!(
                    "refusing to write generated output through a symlink:\n    {}\n  \
                     this path is a symbolic link; writing would modify its target instead of \
                     creating a compiled output.\n  \
                     Remove the link or choose a different output path (-o).",
                    target.display()
                )
                .into());
            }
            if !ft.is_file() {
                return Err(format!(
                    "refusing to write generated output over a non-regular file \
                     (directory, device, or pipe):\n    {}",
                    target.display()
                )
                .into());
            }
            Ok(Inspection::Existing(meta))
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Inspection::Absent),
        Err(e) => Err(format!(
            "refusing to write generated output: could not inspect the destination\n    {}\n  \
             {} — cannot prove it is safe to write.",
            target.display(),
            e
        )
        .into()),
    }
}

fn hardlink_refusal(target: &Path, nlink: u64) -> BoxError {
    format!(
        "refusing to write generated output to a file with a hard-link count of {}:\n    {}\n  \
         a link count above 1 means writing would rewrite the file's other names too; \
         0 means it was unlinked while being inspected.\n  \
         Break the link (or re-run the build) or choose a different output path (-o).",
        nlink,
        target.display()
    )
    .into()
}

/// Preflight one destination against the full plan.
fn decide(o: &PlannedOutput, all: &[PlannedOutput], force: bool) -> Result<Decision, BoxError> {
    match inspect(&o.path)? {
        Inspection::Absent => return Ok(Decision::Create),
        Inspection::Existing(_) => {}
    }

    // Existing scaffold: kept untouched, so no further checks apply.
    if matches!(o.kind, OutputKind::ScaffoldIfAbsent) {
        return Ok(Decision::Keep);
    }

    // Round-6: ALL preflight facts about the existing destination — link
    // count (item 6/7: same rejection the writer applies, so refusals
    // surface before anything else in the graph is written; round-5:
    // Windows too), FILE IDENTITY, and the ownership/content evidence —
    // come from ONE open handle, so they provably describe the same file.
    // The identity travels in the proof and is re-verified on the WRITING
    // fd, which closes the substitution race the evidence alone left open
    // (a different PythScribe-marked file renamed over the destination
    // after preflight).
    let f = open_no_follow_read(&o.path)?;
    let fmeta = f.metadata()?;
    if !fmeta.file_type().is_file() {
        return Err(format!(
            "refusing to write generated output over a non-regular file:\n    {}",
            o.path.display()
        )
        .into());
    }
    {
        let n = link_count_on_fd(&f, &fmeta)?;
        if n != 1 {
            return Err(hardlink_refusal(&o.path, n));
        }
    }
    let identity = file_identity(&f)?;

    if force {
        // --force authorizes destroying THIS file — record its identity and
        // exact bytes so the writer can prove, on the fd, that it is still
        // the very same file.
        let bytes = read_all_on(&f, &o.path)?;
        return Ok(Decision::Overwrite(OverwriteProof {
            identity,
            evidence: Evidence::Bytes(bytes),
        }));
    }

    match &o.kind {
        OutputKind::MarkedText => {
            let mut head = Vec::new();
            if Read::take(&f, 4096).read_to_end(&mut head).is_ok() && looks_pyths_generated(&head)
            {
                Ok(Decision::Overwrite(OverwriteProof {
                    identity,
                    evidence: Evidence::MarkerOnFd,
                }))
            } else {
                Err(format!(
                    "refusing to overwrite a file PythScribe did not generate:\n    {}\n  \
                     it lacks the `{}` marker, so it looks hand-written and would be lost.\n  \
                     Move it aside, choose a different output path (-o), or pass --force.",
                    o.path.display(),
                    GENERATED_MARKER
                )
                .into())
            }
        }
        OutputKind::WasmModule => {
            let bytes = read_all_on(&f, &o.path)?;
            if pyths_codegen_wasm::optimize::has_generated_marker(&bytes) {
                Ok(Decision::Overwrite(OverwriteProof {
                    identity,
                    evidence: Evidence::WasmSectionOnFd,
                }))
            } else {
                Err(format!(
                    "refusing to overwrite a `.wasm` PythScribe cannot prove it created:\n    {}\n  \
                     it lacks the `{}` ownership section. Modules built by PythScribe ≥ 0.2.2 \
                     carry it; pass --force once to adopt an older or foreign file, or build \
                     into a clean output directory.",
                    o.path.display(),
                    pyths_codegen_wasm::optimize::GENERATED_SECTION_NAME
                )
                .into())
            }
        }
        OutputKind::Sidecar { primary } => {
            if primary_is_owned(primary, all)? {
                // The sidecar itself is marker-less, so the writer cannot
                // prove OWNERSHIP on the fd — instead it proves identity:
                // the file's on-disk identity plus the exact bytes whose
                // destruction the owned primary authorizes; anything else on
                // the fd at write time is refused (round-5 fix: no
                // proof-free overwrite path).
                let bytes = read_all_on(&f, &o.path)?;
                Ok(Decision::Overwrite(OverwriteProof {
                    identity,
                    evidence: Evidence::Bytes(bytes),
                }))
            } else {
                Err(format!(
                    "refusing to overwrite an existing file with a generated sidecar \
                     output:\n    {}\n  \
                     it carries no ownership marker, and its primary output\n    {}\n  \
                     is not a PythScribe-generated file it could belong to — so PythScribe \
                     cannot prove the sidecar is its own.\n  \
                     Move it aside, pass --force, or build into a clean output directory.",
                    o.path.display(),
                    primary.display()
                )
                .into())
            }
        }
        OutputKind::ScaffoldIfAbsent => unreachable!("handled above"),
    }
}

/// Is the sidecar's primary output an EXISTING file that PythScribe owns?
/// A fresh (absent) primary returns `false` — absence authorizes nothing
/// (round-3 blocking finding: `app.js` absent + handwritten `app.js.map`
/// must NOT let `--sourcemap` destroy the map).
fn primary_is_owned(primary: &Path, all: &[PlannedOutput]) -> Result<bool, BoxError> {
    let meta = match std::fs::symlink_metadata(primary) {
        Ok(m) => m,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(e) => {
            return Err(format!(
                "refusing to write generated output: could not inspect the primary output\n    \
                 {}\n  {} — cannot prove its sidecar is safe to write.",
                primary.display(),
                e
            )
            .into())
        }
    };
    if !meta.file_type().is_file() {
        return Ok(false);
    }
    // The primary's kind decides which ownership proof applies.
    let is_wasm_primary = all
        .iter()
        .find(|p| p.path == primary)
        .map(|p| matches!(p.kind, OutputKind::WasmModule))
        .unwrap_or_else(|| {
            primary
                .extension()
                .map(|e| e.eq_ignore_ascii_case("wasm"))
                .unwrap_or(false)
        });
    if is_wasm_primary {
        Ok(std::fs::read(primary)
            .map(|b| pyths_codegen_wasm::optimize::has_generated_marker(&b))
            .unwrap_or(false))
    } else {
        Ok(read_head(primary, 4096)
            .map(|h| looks_pyths_generated(&h))
            .unwrap_or(false))
    }
}

fn read_head(path: &Path, limit: u64) -> std::io::Result<Vec<u8>> {
    let f = std::fs::File::open(path)?;
    let mut head = Vec::new();
    f.take(limit).read_to_end(&mut head)?;
    Ok(head)
}

// ---------------------------------------------------------------------------
// The two writers (exclusive create / fd-verified overwrite)
// ---------------------------------------------------------------------------

/// Create a brand-new file EXCLUSIVELY (`O_EXCL`/`CREATE_NEW`). If anything —
/// a real file, or a symlink that raced the preflight — appears at the path,
/// the create fails with `AlreadyExists` and is refused rather than followed.
/// This closes the inspect→write TOCTOU window for every fresh creation.
fn create_new_write(target: &Path, contents: &[u8]) -> Result<FileIdentity, BoxError> {
    match std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(target)
    {
        Ok(mut f) => {
            f.write_all(contents)?;
            // Identity of the file WE created, from our own handle — this is
            // what a later `rewrite` of the same destination must match.
            file_identity(&f)
        }
        Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => Err(format!(
            "refusing to write generated output: the destination appeared while it was being \
             checked:\n    {}\n  Re-run the build.",
            target.display()
        )
        .into()),
        Err(e) => Err(e.into()),
    }
}

/// Hard-link count of an opened file, per platform (round-5: Windows too).
///
///   * unix — from the fstat the writer already performed.
///   * windows — `GetFileInformationByHandle` on the SAME handle, through the
///     safe `winapi-util` wrapper (keeps the compiler `unsafe`-free). A query
///     failure fails CLOSED: if the link count cannot be proven, do not write.
///   * anywhere else — no primitive; treated as 1 (documented residual).
fn link_count_on_fd(f: &std::fs::File, meta: &std::fs::Metadata) -> Result<u64, BoxError> {
    #[cfg(unix)]
    {
        let _ = f;
        use std::os::unix::fs::MetadataExt;
        Ok(meta.nlink())
    }
    #[cfg(windows)]
    {
        let _ = meta;
        let info = winapi_util::file::information(f).map_err(|e| -> BoxError {
            format!(
                "refusing to write generated output: could not query the destination's \
                 hard-link count ({}) — cannot prove it is safe to write.",
                e
            )
            .into()
        })?;
        Ok(info.number_of_links())
    }
    #[cfg(not(any(unix, windows)))]
    {
        let _ = (f, meta);
        Ok(1)
    }
}

/// Open an existing destination READ-ONLY for preflight, no-follow on unix
/// (`libc::O_NOFOLLOW`, per-arch). The preflight facts — link count,
/// identity, evidence — are all read from this one handle so they describe
/// the same file. A failure fails closed.
fn open_no_follow_read(path: &Path) -> Result<std::fs::File, BoxError> {
    let mut opts = std::fs::OpenOptions::new();
    opts.read(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        opts.custom_flags(libc::O_NOFOLLOW);
    }
    opts.open(path).map_err(|e| -> BoxError {
        format!(
            "refusing to write generated output: could not open the destination for \
             pre-flight verification (possible symlink swapped in after inspection):\n    \
             {}\n  {}",
            path.display(),
            e
        )
        .into()
    })
}

/// Read an open handle to the end (used at preflight; the handle is fresh,
/// so this reads from offset 0).
fn read_all_on(mut f: &std::fs::File, path: &Path) -> Result<Vec<u8>, BoxError> {
    let mut bytes = Vec::new();
    f.read_to_end(&mut bytes).map_err(|e| -> BoxError {
        format!(
            "refusing to write generated output: could not read the existing \
             destination for verification:\n    {}\n  {}",
            path.display(),
            e
        )
        .into()
    })?;
    Ok(bytes)
}

/// P5 (round-4 consolidation): overwrite an EXISTING file with the ownership
/// check AND the write on ONE file handle. Correct order (never truncate
/// before verifying): open WITHOUT truncate (`libc::O_NOFOLLOW` on unix — the
/// per-arch-correct constant) → fstat the fd (regular file, `nlink == 1`
/// EXACTLY) → read the fd and verify the proof → and ONLY THEN `set_len(0)`
/// + write on that same handle.
///
/// Doing the proof on the fd (not a fresh path stat) closes BOTH the
/// symlink-swap and the plain-file-swap races: a `victim` moved over `target`
/// after preflight has our handle but not our marker, so it is refused before
/// any truncation. On Windows `O_NOFOLLOW` is unavailable and symlink creation
/// is privilege-gated — a documented residual for the `--force`/sidecar path;
/// the fd proof still catches a swapped-in file for text and wasm outputs.
fn overwrite_on_fd(
    target: &Path,
    contents: &[u8],
    proof: &OverwriteProof,
) -> Result<FileIdentity, BoxError> {
    let mut opts = std::fs::OpenOptions::new();
    opts.read(true).write(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        // ROOT FIX (round-4 blocking finding): use libc's per-architecture
        // O_NOFOLLOW. The previous hardcoded 0x20000 was the x86 value and is
        // WRONG on aarch64-linux (0x8000) — a released npm target — which made
        // the no-follow guard silently inert there.
        opts.custom_flags(libc::O_NOFOLLOW);
    }
    let mut f = opts
        .open(target)
        .map_err(|e| -> BoxError {
            format!(
                "refusing to write generated output: could not open the destination no-follow \
                 (possible symlink swapped in after inspection):\n    {}\n  {}",
                target.display(),
                e
            )
            .into()
        })?;
    let meta = f.metadata()?;
    if !meta.file_type().is_file() {
        return Err(format!(
            "refusing to write generated output over a non-regular file:\n    {}",
            target.display()
        )
        .into());
    }
    {
        // EXACTLY 1: >1 is a hard link (writing rewrites the other names);
        // 0 means the destination was unlinked after our open — this handle
        // is an orphan and "success" would write to a file that no longer
        // exists at the destination (round-3 should-fix). Round-5: enforced
        // on Windows too, on this same handle.
        let n = link_count_on_fd(&f, &meta)?;
        if n != 1 {
            return Err(hardlink_refusal(target, n));
        }
    }
    // Round-6: FILE IDENTITY first — this handle must be the very file
    // preflight authorized overwriting. Without this, a DIFFERENT
    // PythScribe-marked file renamed over the destination after preflight
    // would pass the evidence check below and be destroyed.
    let identity = file_identity(&f)?;
    if identity != proof.identity {
        return Err(format!(
            "refusing to write generated output: the destination was replaced while the \
             build was running:\n    {}\n  \
             it is no longer the same file the pre-flight check authorized overwriting \
             (a different file — even a PythScribe-generated one — was moved into place).\n  \
             Re-run the build.",
            target.display()
        )
        .into());
    }
    match &proof.evidence {
        Evidence::MarkerOnFd => {
            let mut head = Vec::new();
            Read::by_ref(&mut f).take(4096).read_to_end(&mut head)?;
            if !looks_pyths_generated(&head) {
                return Err(format!(
                    "refusing to overwrite a file PythScribe did not generate:\n    {}\n  \
                     it lacks the `{}` marker, so it looks hand-written and would be lost.\n  \
                     Move it aside, choose a different output path (-o), or pass --force.",
                    target.display(),
                    GENERATED_MARKER
                )
                .into());
            }
        }
        Evidence::WasmSectionOnFd => {
            let mut all = Vec::new();
            Read::by_ref(&mut f).read_to_end(&mut all)?;
            if !pyths_codegen_wasm::optimize::has_generated_marker(&all) {
                return Err(format!(
                    "refusing to overwrite a `.wasm` PythScribe cannot prove it created \
                     (it lacks the `{}` ownership section):\n    {}\n  Pass --force to adopt it.",
                    pyths_codegen_wasm::optimize::GENERATED_SECTION_NAME,
                    target.display()
                )
                .into());
            }
        }
        Evidence::Bytes(expected) => {
            // Round-5: no proof-free overwrite path. The fd's current content
            // must be byte-identical to what preflight authorized destroying
            // (the identity check above already refused a different-file
            // swap; this refuses a same-file content change).
            let mut all = Vec::new();
            Read::by_ref(&mut f).read_to_end(&mut all)?;
            if &all != expected {
                return Err(format!(
                    "refusing to write generated output: the destination changed while the \
                     build was running:\n    {}\n  \
                     its content no longer matches what the pre-flight check authorized \
                     overwriting.\n  Re-run the build.",
                    target.display()
                )
                .into());
            }
        }
    }
    // Identity + ownership proven on THIS handle — now it is safe to
    // truncate + write. The identity is returned so the plan can bind a
    // later `rewrite` to this exact file (truncating in place preserves it).
    f.seek(SeekFrom::Start(0))?;
    f.set_len(0)?;
    f.write_all(contents)?;
    Ok(identity)
}

// ---------------------------------------------------------------------------
// User-named outputs (`expand -o`) — no ownership marker
// ---------------------------------------------------------------------------

/// Write to a path the USER explicitly named on the command line (`pyths
/// expand -o <path>`), where the content is NOT PythScribe-marked generated
/// output: `expand` emits clean canonical `.ps`, whose only legal comment
/// syntax is Python's `#`, so the `// @generated` ownership marker cannot be
/// embedded without corrupting the source. An explicit `-o` is itself the
/// authorization to write there (like a shell `>` redirection), so no marker
/// gate applies — but this routes through the SAME no-follow / non-regular-file
/// machinery as every other generated-output writer, closing the CWE-59
/// write-*through*-a-symlink hole a bare `std::fs::write` leaves open:
///
///   * a pre-existing symlink or non-regular file (dir/device/pipe) at the
///     destination is REFUSED (via [`inspect`], which uses `symlink_metadata`
///     so a link is seen, not followed);
///   * a fresh path is created EXCLUSIVELY (`O_EXCL`/`CREATE_NEW`), so a file —
///     or a symlink — racing the check is refused, not followed;
///   * an existing plain regular file is overwritten on a no-follow fd whose
///     regular-file + `nlink == 1` invariants are re-verified on the writing
///     handle (so a symlink or hard link swapped in after `inspect` is refused
///     on unix; the Windows residual is the module-documented one — no
///     `O_NOFOLLOW`, symlink creation privilege-gated).
pub fn write_user_named(path: &Path, contents: &[u8]) -> Result<(), BoxError> {
    match inspect(path)? {
        Inspection::Absent => {
            create_new_write(path, contents)?;
            Ok(())
        }
        Inspection::Existing(_) => overwrite_plain_on_fd(path, contents),
    }
}

/// Overwrite an existing plain file the user explicitly named. No ownership
/// proof (the explicit `-o` is the authorization), but still fd-verified the
/// same way [`overwrite_on_fd`] is: open WITHOUT truncate (`libc::O_NOFOLLOW`
/// on unix — the per-arch constant), confirm the fd is a regular file with a
/// link count of EXACTLY 1, and only then `set_len(0)` + write on that same
/// handle — so a symlink or hard link swapped in after `inspect` is refused
/// rather than followed.
fn overwrite_plain_on_fd(target: &Path, contents: &[u8]) -> Result<(), BoxError> {
    let mut opts = std::fs::OpenOptions::new();
    opts.read(true).write(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        opts.custom_flags(libc::O_NOFOLLOW);
    }
    let mut f = opts.open(target).map_err(|e| -> BoxError {
        format!(
            "refusing to write output: could not open the destination no-follow \
             (possible symlink swapped in after inspection):\n    {}\n  {}",
            target.display(),
            e
        )
        .into()
    })?;
    let meta = f.metadata()?;
    if !meta.file_type().is_file() {
        return Err(format!(
            "refusing to write output over a non-regular file:\n    {}",
            target.display()
        )
        .into());
    }
    let n = link_count_on_fd(&f, &meta)?;
    if n != 1 {
        return Err(hardlink_refusal(target, n));
    }
    f.seek(SeekFrom::Start(0))?;
    f.set_len(0)?;
    f.write_all(contents)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static N: AtomicU64 = AtomicU64::new(0);
        let id = N.fetch_add(1, Ordering::SeqCst);
        let d = std::env::temp_dir().join(format!(
            "pyths_sw_{}_{}_{}",
            tag,
            std::process::id(),
            id
        ));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[cfg(unix)]
    fn try_symlink(target: &Path, link: &Path) -> std::io::Result<()> {
        std::os::unix::fs::symlink(target, link)
    }
    #[cfg(windows)]
    fn try_symlink(target: &Path, link: &Path) -> std::io::Result<()> {
        std::os::windows::fs::symlink_file(target, link)
    }

    fn marked(body: &str) -> String {
        format!("{}{}", generated_header(), body)
    }

    fn marked_wasm() -> Vec<u8> {
        let mut m = b"\0asm\x01\0\0\0".to_vec();
        pyths_codegen_wasm::optimize::append_generated_marker(&mut m);
        m
    }

    /// Build a proof for direct `overwrite_on_fd` calls, carrying the
    /// CURRENT identity of `path` (what preflight would have captured).
    fn proof_for(path: &Path, evidence: Evidence) -> OverwriteProof {
        let f = std::fs::File::open(path).unwrap();
        OverwriteProof {
            identity: file_identity(&f).unwrap(),
            evidence,
        }
    }

    // ── the single-output surface (A8 heritage) ────────────────────────────

    #[test]
    fn creates_a_fresh_marked_text() {
        let d = scratch("fresh");
        let t = d.join("out.js");
        write_single(&t, b"CODE", OutputKind::MarkedText, false).unwrap();
        assert_eq!(std::fs::read(&t).unwrap(), b"CODE");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn refuses_to_clobber_handwritten_without_marker() {
        let d = scratch("handwritten");
        let t = d.join("Counter.js");
        std::fs::write(&t, b"export const mine = 1; // hand-written").unwrap();
        let err = write_single(&t, b"GENERATED", OutputKind::MarkedText, false).unwrap_err();
        assert!(err.to_string().contains("did not generate"), "err: {}", err);
        assert_eq!(
            std::fs::read(&t).unwrap(),
            b"export const mine = 1; // hand-written"
        );
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn overwrites_own_marked_output() {
        let d = scratch("marked");
        let t = d.join("out.js");
        std::fs::write(&t, marked("old body").as_bytes()).unwrap();
        write_single(&t, b"NEWBODY", OutputKind::MarkedText, false).unwrap();
        assert_eq!(std::fs::read(&t).unwrap(), b"NEWBODY");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn force_overwrites_handwritten() {
        let d = scratch("force");
        let t = d.join("out.js");
        std::fs::write(&t, b"hand-written").unwrap();
        write_single(&t, b"NEW", OutputKind::MarkedText, true).unwrap();
        assert_eq!(std::fs::read(&t).unwrap(), b"NEW");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn refuses_to_write_through_a_symlink() {
        let d = scratch("symlink");
        let victim = d.join("victim.txt");
        std::fs::write(&victim, b"ORIGINAL-SECRET").unwrap();
        let link = d.join("app.js");
        // Creating a symlink may require privilege (Windows without dev mode).
        // Skip cleanly if the OS denies it — the logic is still covered on
        // unix/CI. This is the documented Windows residual.
        if try_symlink(&victim, &link).is_err() {
            eprintln!("skipping symlink test: OS denied symlink creation");
            let _ = std::fs::remove_dir_all(&d);
            return;
        }
        let err = write_single(&link, b"PWNED", OutputKind::MarkedText, false).unwrap_err();
        assert!(err.to_string().contains("symlink"), "err: {}", err);
        assert_eq!(std::fs::read(&victim).unwrap(), b"ORIGINAL-SECRET");
        // Even --force must not write through a symlink.
        let err2 = write_single(&link, b"PWNED", OutputKind::MarkedText, true).unwrap_err();
        assert!(err2.to_string().contains("symlink"), "err2: {}", err2);
        assert_eq!(std::fs::read(&victim).unwrap(), b"ORIGINAL-SECRET");
        let _ = std::fs::remove_dir_all(&d);
    }

    /// Item 1 regression: even if every pre-open inspection were bypassed, the
    /// fd writer itself must refuse a symlink — that is what O_NOFOLLOW is
    /// for, and it must be the per-arch libc constant, not a hardcoded value.
    #[cfg(unix)]
    #[test]
    fn fd_writer_alone_refuses_a_symlink_o_nofollow() {
        let d = scratch("nofollow");
        let victim = d.join("victim.txt");
        std::fs::write(&victim, marked("victim-with-marker").as_bytes()).unwrap();
        let link = d.join("swapped.js");
        try_symlink(&victim, &link).unwrap();
        // Call the overwrite path DIRECTLY on the symlink (as if it was
        // swapped in after preflight). Open must fail with ELOOP.
        let err =
            overwrite_on_fd(&link, b"PWNED", &proof_for(&link, Evidence::MarkerOnFd)).unwrap_err();
        assert!(
            err.to_string().contains("no-follow"),
            "err: {}",
            err
        );
        assert_eq!(
            std::fs::read(&victim).unwrap(),
            marked("victim-with-marker").as_bytes()
        );
        let _ = std::fs::remove_dir_all(&d);
    }

    /// The marker is verified on the SAME fd that is truncated: a swapped-in
    /// unmarked file is refused by the fd proof even when preflight was told
    /// the file is ours.
    #[test]
    fn fd_proof_refuses_swapped_in_unmarked_file() {
        let d = scratch("fdswap");
        let t = d.join("out.js");
        std::fs::write(&t, b"VICTIM CONTENT (no marker)").unwrap();
        let err =
            overwrite_on_fd(&t, b"NEW", &proof_for(&t, Evidence::MarkerOnFd)).unwrap_err();
        assert!(err.to_string().contains("did not generate"), "err: {}", err);
        assert_eq!(std::fs::read(&t).unwrap(), b"VICTIM CONTENT (no marker)");
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── item 7: hard-link count must be EXACTLY 1 ──────────────────────────
    // Round-5: also enforced on Windows (GetFileInformationByHandle), so the
    // test runs everywhere hard links exist (NTFS included).

    #[test]
    fn refuses_hardlinked_destination_even_with_marker() {
        let d = scratch("hardlink");
        let orig = d.join("out.js");
        std::fs::write(&orig, marked("shared").as_bytes()).unwrap();
        let other = d.join("backup.js");
        std::fs::hard_link(&orig, &other).unwrap();
        // Preflight refuses...
        let err = write_single(&orig, b"NEW", OutputKind::MarkedText, false).unwrap_err();
        assert!(err.to_string().contains("hard-link"), "err: {}", err);
        // ...and so does the fd writer on its own.
        let err2 =
            overwrite_on_fd(&orig, b"NEW", &proof_for(&orig, Evidence::MarkerOnFd)).unwrap_err();
        assert!(err2.to_string().contains("hard-link"), "err2: {}", err2);
        assert_eq!(std::fs::read(&other).unwrap(), marked("shared").as_bytes());
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── item 3: a fresh primary authorizes NOTHING ─────────────────────────

    #[test]
    fn fresh_primary_does_not_authorize_sidecar_overwrite() {
        let d = scratch("freshprimary");
        let js = d.join("app.js"); // absent — a FRESH primary
        let map = d.join("app.js.map");
        std::fs::write(&map, b"{\"handwritten\":true}").unwrap();
        let planned = [
            PlannedOutput::marked_text(&js),
            PlannedOutput::sidecar(&map, &js),
        ];
        let err = OutputPlan::preflight(&planned, false).unwrap_err();
        assert!(err.to_string().contains("sidecar"), "err: {}", err);
        // Nothing was written or destroyed.
        assert!(!js.exists());
        assert_eq!(std::fs::read(&map).unwrap(), b"{\"handwritten\":true}");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn owned_primary_authorizes_sidecar_rebuild() {
        let d = scratch("ownedprimary");
        let js = d.join("app.js");
        let map = d.join("app.js.map");
        std::fs::write(&js, marked("old build").as_bytes()).unwrap();
        std::fs::write(&map, b"{\"version\":3}").unwrap();
        let planned = [
            PlannedOutput::marked_text(&js),
            PlannedOutput::sidecar(&map, &js),
        ];
        let plan = OutputPlan::preflight(&planned, false).unwrap();
        plan.write(&js, marked("new build").as_bytes()).unwrap();
        plan.write(&map, b"{\"version\":3,\"new\":true}").unwrap();
        assert_eq!(std::fs::read(&map).unwrap(), b"{\"version\":3,\"new\":true}");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn unowned_wasm_primary_does_not_authorize_cert_overwrite() {
        let d = scratch("foreignwasm");
        let wasm = d.join("app.wasm");
        let cert = d.join("app.js.wasm.cert.json");
        std::fs::write(&wasm, b"\0asm\x01\0\0\0").unwrap(); // valid, NOT ours
        std::fs::write(&cert, b"{\"handwritten\":true}").unwrap();
        let planned = [
            PlannedOutput::wasm(&wasm),
            PlannedOutput::sidecar(&cert, &wasm),
        ];
        let err = OutputPlan::preflight(&planned, false).unwrap_err();
        // Either refusal is acceptable; nothing must be written.
        assert!(
            err.to_string().contains("cannot prove") || err.to_string().contains("sidecar"),
            "err: {}",
            err
        );
        assert_eq!(std::fs::read(&cert).unwrap(), b"{\"handwritten\":true}");
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── item 4: the tool's OWN wasm rebuild works without --force ──────────

    #[test]
    fn own_wasm_rebuild_succeeds_without_force() {
        let d = scratch("wasmrebuild");
        let wasm = d.join("app.wasm");
        // First build.
        let planned = [PlannedOutput::wasm(&wasm)];
        let plan = OutputPlan::preflight(&planned, false).unwrap();
        plan.write(&wasm, &marked_wasm()).unwrap();
        // Second build — no --force needed: the module proves its own origin.
        let plan2 = OutputPlan::preflight(&planned, false).unwrap();
        plan2.write(&wasm, &marked_wasm()).unwrap();
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn foreign_wasm_refused_without_force_adopted_with_force() {
        let d = scratch("wasmforeign");
        let wasm = d.join("app.wasm");
        std::fs::write(&wasm, b"\0asm\x01\0\0\0").unwrap(); // no ownership section
        let planned = [PlannedOutput::wasm(&wasm)];
        let err = OutputPlan::preflight(&planned, false).unwrap_err();
        assert!(err.to_string().contains("cannot prove"), "err: {}", err);
        assert_eq!(std::fs::read(&wasm).unwrap(), b"\0asm\x01\0\0\0");
        // --force adopts it once; from then on it is marked and rebuilds free.
        let plan = OutputPlan::preflight(&planned, true).unwrap();
        plan.write(&wasm, &marked_wasm()).unwrap();
        let plan2 = OutputPlan::preflight(&planned, false).unwrap();
        plan2.write(&wasm, &marked_wasm()).unwrap();
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── item 5: the WHOLE graph is preflighted before any write ────────────

    #[test]
    fn complete_graph_refusal_writes_nothing() {
        // wasm+glue absent (would be written first in the old code), but the
        // eventual .js destination is hand-written: the preflight must refuse
        // BEFORE the wasm cluster hits the disk.
        let d = scratch("wholegraph");
        let wasm = d.join("app.wasm");
        let glue = d.join("app.glue.js");
        let js = d.join("app.js");
        std::fs::write(&js, b"hand-written entry").unwrap();
        let planned = [
            PlannedOutput::wasm(&wasm),
            PlannedOutput::marked_text(&glue),
            PlannedOutput::marked_text(&js),
        ];
        let err = OutputPlan::preflight(&planned, false).unwrap_err();
        assert!(err.to_string().contains("did not generate"), "err: {}", err);
        assert!(!wasm.exists(), "wasm must not be written on a refused graph");
        assert!(!glue.exists(), "glue must not be written on a refused graph");
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── item 6: destination aliasing ────────────────────────────────────────

    #[test]
    fn aliased_destinations_are_rejected_up_front() {
        let d = scratch("alias");
        // `--target deno -o worker.wasm`: entry and wasm collapse to one path.
        let out = d.join("worker.wasm");
        let planned = [
            PlannedOutput::wasm(&out),
            PlannedOutput::marked_text(&out),
        ];
        let err = OutputPlan::preflight(&planned, false).unwrap_err();
        assert!(err.to_string().contains("same"), "err: {}", err);
        assert!(!out.exists());
        // Different spellings of one path also collide.
        let a = d.join("app.js");
        let b = d.join(".").join("app.js");
        let planned2 = [
            PlannedOutput::marked_text(&a),
            PlannedOutput::marked_text(&b),
        ];
        assert!(OutputPlan::preflight(&planned2, false).is_err());
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── the fail-closed plan surface ────────────────────────────────────────

    #[test]
    fn unplanned_write_is_refused() {
        let d = scratch("unplanned");
        let a = d.join("a.js");
        let rogue = d.join("rogue.js");
        let plan = OutputPlan::preflight(&[PlannedOutput::marked_text(&a)], false).unwrap();
        let err = plan.write(&rogue, b"X").unwrap_err();
        assert!(err.to_string().contains("unplanned"), "err: {}", err);
        assert!(!rogue.exists());
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── scaffolds (SEC #12 heritage) ────────────────────────────────────────

    #[test]
    fn scaffold_keeps_existing_and_creates_when_absent() {
        let d = scratch("scaffold");
        let existing = d.join("wrangler.toml");
        std::fs::write(&existing, b"name = \"mine\"\n").unwrap();
        let fresh = d.join("package.json");
        let planned = [
            PlannedOutput::scaffold(&existing),
            PlannedOutput::scaffold(&fresh),
        ];
        let plan = OutputPlan::preflight(&planned, false).unwrap();
        assert!(!plan.write(&existing, b"GEN").unwrap()); // kept
        assert_eq!(std::fs::read(&existing).unwrap(), b"name = \"mine\"\n");
        assert!(plan.write(&fresh, b"{}").unwrap()); // created
        assert_eq!(std::fs::read(&fresh).unwrap(), b"{}");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn scaffold_refuses_symlink_including_dangling() {
        // SEC #12: the real vector is a DANGLING symlink — `Path::exists`
        // reports it absent, so a naive write creates its target.
        let d = scratch("scaffold_link");
        let link = d.join("wrangler.toml");
        let dangling = d.join("does-not-exist.txt");
        if try_symlink(&dangling, &link).is_err() {
            let _ = std::fs::remove_dir_all(&d);
            return; // OS denied symlink creation (Windows without dev mode)
        }
        let err = OutputPlan::preflight(&[PlannedOutput::scaffold(&link)], false).unwrap_err();
        assert!(err.to_string().contains("symlink"), "err: {}", err);
        assert!(!dangling.exists(), "the link target must NOT be created");
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── round-5: no proof-free overwrite path ───────────────────────────────

    #[test]
    fn sidecar_swapped_after_preflight_is_refused_on_the_fd() {
        let d = scratch("sidecarswap");
        let js = d.join("app.js");
        let map = d.join("app.js.map");
        std::fs::write(&js, marked("owned build").as_bytes()).unwrap();
        std::fs::write(&map, b"{\"version\":3}").unwrap();
        let planned = [
            PlannedOutput::marked_text(&js),
            PlannedOutput::sidecar(&map, &js),
        ];
        let plan = OutputPlan::preflight(&planned, false).unwrap();
        // Attacker swaps an unowned file over the map AFTER preflight.
        std::fs::write(&map, b"VICTIM DATA").unwrap();
        let err = plan.write(&map, b"{\"new\":true}").unwrap_err();
        assert!(err.to_string().contains("changed while"), "err: {}", err);
        assert_eq!(std::fs::read(&map).unwrap(), b"VICTIM DATA");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn force_swap_after_preflight_is_refused_on_the_fd() {
        let d = scratch("forceswap");
        let t = d.join("out.js");
        std::fs::write(&t, b"the file --force authorized destroying").unwrap();
        let plan =
            OutputPlan::preflight(&[PlannedOutput::marked_text(&t)], true).unwrap();
        // Swap in a DIFFERENT file after preflight: --force must not carry over.
        std::fs::write(&t, b"a different victim").unwrap();
        let err = plan.write(&t, b"NEW").unwrap_err();
        assert!(err.to_string().contains("changed while"), "err: {}", err);
        assert_eq!(std::fs::read(&t).unwrap(), b"a different victim");
        // Unchanged content still writes fine under --force.
        let plan2 =
            OutputPlan::preflight(&[PlannedOutput::marked_text(&t)], true).unwrap();
        plan2.write(&t, b"NEW").unwrap();
        assert_eq!(std::fs::read(&t).unwrap(), b"NEW");
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── round-5: wasm-opt placement goes through the plan (rewrite) ─────────

    #[test]
    fn rewrite_replaces_own_artifact_and_refuses_a_swap() {
        let d = scratch("rewrite");
        let wasm = d.join("app.wasm");
        let planned = [PlannedOutput::wasm(&wasm)];
        let plan = OutputPlan::preflight(&planned, false).unwrap();
        plan.write(&wasm, &marked_wasm()).unwrap();
        // The optimized module (still marker-bearing) replaces our own write.
        let mut optimized = marked_wasm();
        optimized.extend_from_slice(&[0x00, 0x01, 0x00]); // any trailing custom section
        plan.rewrite(&wasm, &optimized).unwrap();
        assert_eq!(std::fs::read(&wasm).unwrap(), optimized);
        // A file swapped in WITHOUT the ownership section is refused.
        std::fs::write(&wasm, b" asm   ").unwrap();
        let err = plan.rewrite(&wasm, &optimized).unwrap_err();
        assert!(err.to_string().contains("cannot prove"), "err: {}", err);
        assert_eq!(std::fs::read(&wasm).unwrap(), b" asm   ");
        // An unplanned destination is refused outright.
        let rogue = d.join("rogue.wasm");
        std::fs::write(&rogue, &marked_wasm()).unwrap();
        let err2 = plan.rewrite(&rogue, &optimized).unwrap_err();
        assert!(err2.to_string().contains("unplanned"), "err2: {}", err2);
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── round-6: identity binds the write to the PREFLIGHTED file ───────────
    // The evidence alone (marker / wasm section / bytes) is forgeable by
    // construction; the identity captured at preflight is what refuses a
    // DIFFERENT file — even a genuinely PythScribe-generated one — moved
    // over the destination afterwards.

    #[test]
    fn marked_text_swap_after_preflight_is_refused() {
        let d = scratch("idswaptext");
        let t = d.join("out.js");
        std::fs::write(&t, marked("the preflighted build").as_bytes()).unwrap();
        let plan = OutputPlan::preflight(&[PlannedOutput::marked_text(&t)], false).unwrap();
        // Attacker renames a DIFFERENT PythScribe-marked file over it.
        let decoy = d.join("decoy.js");
        std::fs::write(&decoy, marked("a different marked file").as_bytes()).unwrap();
        std::fs::rename(&decoy, &t).unwrap();
        let err = plan.write(&t, b"NEW").unwrap_err();
        assert!(err.to_string().contains("replaced"), "err: {}", err);
        assert_eq!(
            std::fs::read(&t).unwrap(),
            marked("a different marked file").as_bytes()
        );
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn marked_wasm_swap_after_preflight_is_refused() {
        let d = scratch("idswapwasm");
        let t = d.join("app.wasm");
        std::fs::write(&t, marked_wasm()).unwrap();
        let plan = OutputPlan::preflight(&[PlannedOutput::wasm(&t)], false).unwrap();
        // A different, genuinely marker-bearing module is swapped in.
        let decoy = d.join("decoy.wasm");
        let mut other = marked_wasm();
        other.extend_from_slice(&[0x00, 0x01, 0x00]);
        std::fs::write(&decoy, &other).unwrap();
        std::fs::rename(&decoy, &t).unwrap();
        let err = plan.write(&t, &marked_wasm()).unwrap_err();
        assert!(err.to_string().contains("replaced"), "err: {}", err);
        assert_eq!(std::fs::read(&t).unwrap(), other);
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn force_swap_of_byte_identical_copy_is_refused() {
        // Even a byte-for-byte COPY swapped in after preflight is a different
        // file (different identity) and must be refused — --force authorized
        // destroying the file it inspected, not a lookalike.
        let d = scratch("idswapforce");
        let t = d.join("out.js");
        std::fs::write(&t, b"authorized bytes").unwrap();
        let plan = OutputPlan::preflight(&[PlannedOutput::marked_text(&t)], true).unwrap();
        let copy = d.join("copy.js");
        std::fs::write(&copy, b"authorized bytes").unwrap();
        std::fs::rename(&copy, &t).unwrap();
        let err = plan.write(&t, b"NEW").unwrap_err();
        assert!(err.to_string().contains("replaced"), "err: {}", err);
        assert_eq!(std::fs::read(&t).unwrap(), b"authorized bytes");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn rewrite_refuses_a_swapped_in_marked_file() {
        // rewrite is bound to the identity of the file THIS plan wrote — a
        // marker-bearing module swapped in between write and rewrite fails
        // the identity check even though its evidence is valid.
        let d = scratch("idswaprewrite");
        let wasm = d.join("app.wasm");
        let plan = OutputPlan::preflight(&[PlannedOutput::wasm(&wasm)], false).unwrap();
        plan.write(&wasm, &marked_wasm()).unwrap();
        let decoy = d.join("decoy.wasm");
        let mut other = marked_wasm();
        other.extend_from_slice(&[0x00, 0x01, 0x00]);
        std::fs::write(&decoy, &other).unwrap();
        std::fs::rename(&decoy, &wasm).unwrap();
        let err = plan.rewrite(&wasm, &marked_wasm()).unwrap_err();
        assert!(err.to_string().contains("replaced"), "err: {}", err);
        assert_eq!(std::fs::read(&wasm).unwrap(), other);
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn rewrite_of_an_unwritten_output_is_refused() {
        // A planned destination that this invocation never wrote has no
        // written-identity to bind to — rewrite must fail closed.
        let d = scratch("rewriteunwritten");
        let wasm = d.join("app.wasm");
        std::fs::write(&wasm, marked_wasm()).unwrap();
        let plan = OutputPlan::preflight(&[PlannedOutput::wasm(&wasm)], false).unwrap();
        let err = plan.rewrite(&wasm, &marked_wasm()).unwrap_err();
        assert!(err.to_string().contains("has not written"), "err: {}", err);
        assert_eq!(std::fs::read(&wasm).unwrap(), marked_wasm());
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── write_user_named (`expand -o`) — no marker, symlink-safe ────────────

    #[test]
    fn user_named_creates_fresh_and_overwrites_plain() {
        let d = scratch("usernamed_ok");
        let t = d.join("out.ps");
        // Fresh path → created (no marker required; content is verbatim).
        write_user_named(&t, b"X = 1\n").unwrap();
        assert_eq!(std::fs::read(&t).unwrap(), b"X = 1\n");
        // Existing plain file → overwritten (explicit -o authorizes it), even
        // though it carries NO `@generated` marker.
        write_user_named(&t, b"Y = 2\n").unwrap();
        assert_eq!(std::fs::read(&t).unwrap(), b"Y = 2\n");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn user_named_refuses_to_write_through_a_symlink() {
        // Matches the bundle.rs / A8 symlink-safety tests: a `-o` pointing at a
        // symlink must NOT overwrite the link's target (CWE-59).
        let d = scratch("usernamed_symlink");
        let victim = d.join("victim.txt");
        std::fs::write(&victim, b"ORIGINAL-SECRET").unwrap();
        let link = d.join("out.ps");
        if try_symlink(&victim, &link).is_err() {
            eprintln!("skipping symlink test: OS denied symlink creation");
            let _ = std::fs::remove_dir_all(&d);
            return;
        }
        let err = write_user_named(&link, b"PWNED").unwrap_err();
        assert!(err.to_string().contains("symlink"), "err: {}", err);
        assert_eq!(std::fs::read(&victim).unwrap(), b"ORIGINAL-SECRET");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn user_named_refuses_non_regular_file() {
        // A directory (or any non-regular file) at the destination is refused,
        // not written into.
        let d = scratch("usernamed_dir");
        let sub = d.join("out.ps");
        std::fs::create_dir(&sub).unwrap();
        let err = write_user_named(&sub, b"X").unwrap_err();
        assert!(
            err.to_string().contains("non-regular") || err.to_string().contains("directory"),
            "err: {}",
            err
        );
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn user_named_refuses_hardlinked_destination() {
        let d = scratch("usernamed_hardlink");
        let orig = d.join("out.ps");
        std::fs::write(&orig, b"shared\n").unwrap();
        let other = d.join("backup.ps");
        std::fs::hard_link(&orig, &other).unwrap();
        let err = write_user_named(&orig, b"NEW").unwrap_err();
        assert!(err.to_string().contains("hard-link"), "err: {}", err);
        assert_eq!(std::fs::read(&other).unwrap(), b"shared\n");
        let _ = std::fs::remove_dir_all(&d);
    }

    // ── P4 heritage — marker position ───────────────────────────────────────

    #[test]
    fn p4_marker_must_be_at_start_not_substring() {
        let owned = marked("export const x = 1;\n");
        assert!(looks_pyths_generated(owned.as_bytes()));
        let doc = b"// Preserve the literal \"@generated by PythScribe\" for docs\nconst mine = 1;\n";
        assert!(!looks_pyths_generated(doc));
        let indented = b"const x = 1; // @generated by PythScribe\n";
        assert!(!looks_pyths_generated(indented));
    }
}
