// @generated by PythScribe — do not edit; regenerate with `pyths compile`.
import { Exception, pyAdd, pyBool, pyGetItem, pyStr } from "pyths-runtime";

import { Component, createElement as h } from "react";
export class Hello extends Component {
    render() {
        return h("h1", null, pyAdd("hi ", this.props.name));
    }
}
Hello.__name__ = "Hello";
export class Counter extends Component {
    constructor(props) {
        super(props);
        this.state = ({"count": 0});
    }
    bump() {
        this.setState(({"count": pyAdd(pyGetItem(this.state, "count"), 1)}));
    }
    render() {
        return h("div", null, pyAdd("count=", pyStr(pyGetItem(this.state, "count"))));
    }
}
Counter.__name__ = "Counter";
Counter.__pyparams__ = ["props"];
export class Boundary extends Component {
    constructor(props) {
        super(props);
        this.state = ({"hasError": false});
    }
    static getDerivedStateFromError(error) {
        return ({"hasError": true});
    }
    componentDidCatch(error, info) {
    }
    render() {
        if (pyBool(pyGetItem(this.state, "hasError"))) {
            return h("p", null, "fallback");
        }
        return this.props.children;
    }
}
Boundary.__name__ = "Boundary";
Boundary.__pyparams__ = ["props"];
Boundary.prototype.getDerivedStateFromError = Boundary.getDerivedStateFromError;
Boundary.getDerivedStateFromError.__pyparams__ = ["error"];
Boundary.prototype.componentDidCatch.__pyparams__ = ["error", "info"];
export function Boom(props) {
    throw new Exception("kaboom");
}
Boom.__pyparams__ = ["props"];
