// @generated by PythScribe — do not edit; regenerate with `pyths compile`.
// Auto-generated by PythScribe compiler — do not edit.
import { pyAdd, pyMod, pyMul } from "pyths-runtime";
const __wasm = await (async () => {
  const imports = {};
  const url = new URL('./auto_route_demo.wasm', import.meta.url);
  const isNode = typeof globalThis.process !== 'undefined'
    && globalThis.process.versions != null
    && typeof globalThis.process.versions.node === 'string';
  if (isNode) {
    const { readFile } = await import('node:fs/promises');
    const { fileURLToPath } = await import('node:url');
    const bytes = await readFile(fileURLToPath(url));
    return (await WebAssembly.instantiate(bytes, imports)).instance.exports;
  }
  if (typeof WebAssembly.instantiateStreaming === 'function') {
    return (await WebAssembly.instantiateStreaming(fetch(url), imports)).instance.exports;
  }
  const bytes = await fetch(url).then(r => r.arrayBuffer());
  return (await WebAssembly.instantiate(bytes, imports)).instance.exports;
})();
const __i64ToJs = (v) => (v >= -9007199254740991n && v <= 9007199254740991n ? Number(v) : v);
const __i64Oob = (v) => typeof v === "bigint" && (v > 9223372036854775807n || v < -9223372036854775808n);

// #358: exact JS twins of the WASM-compiled functions. When a call
// would exceed i64 (the `__ovf` flag, or an out-of-range argument),
// the wrapper transparently re-runs it on these arbitrary-precision
// implementations — the WASM fast path never returns a wrapped value.
const __jsfb = (() => {

function fibonacci(n) {
    let c;
    let a = 0;
    let b = 1;
    let i = 0;
    while ((i < n)) {
        c = pyAdd(a, b);
        a = b;
        b = c;
        i = pyAdd(i, 1);
    }
    return a;
}
fibonacci.__pyparams__ = ["n"];
function prime_count(limit) {
    let is_prime;
    let d;
    let count = 0;
    let n = 2;
    while ((n < limit)) {
        is_prime = 1;
        d = 2;
        while ((pyMul(d, d) <= n)) {
            if ((pyMod(n, d) === 0)) {
                is_prime = 0;
                d = limit;
            }
            d = pyAdd(d, 1);
        }
        if ((is_prime === 1)) {
            count = pyAdd(count, 1);
        }
        n = pyAdd(n, 1);
    }
    return count;
}
prime_count.__pyparams__ = ["limit"];
return { fibonacci, prime_count };
})();
const __isWasmFault = (e) => (typeof WebAssembly !== "undefined" && e instanceof WebAssembly.RuntimeError) || e instanceof RangeError;

export function fibonacci(n) {
  try {
  if (__i64Oob(n)) return __jsfb.fibonacci(n);
  const __raw = __wasm.fibonacci((typeof n === "bigint" ? n : BigInt(Math.trunc(n))));
  if (__wasm.__ovf.value) {
    __wasm.__ovf.value = 0;
    return __jsfb.fibonacci(n);
  }
  return __i64ToJs(__raw);
  } catch (__e) {
    if (__isWasmFault(__e)) return __jsfb.fibonacci(n);
    throw __e;
  }
}
fibonacci.__pyparams__ = ["n"];

export function prime_count(limit) {
  try {
  if (__i64Oob(limit)) return __jsfb.prime_count(limit);
  const __raw = __wasm.prime_count((typeof limit === "bigint" ? limit : BigInt(Math.trunc(limit))));
  if (__wasm.__ovf.value) {
    __wasm.__ovf.value = 0;
    return __jsfb.prime_count(limit);
  }
  return __i64ToJs(__raw);
  } catch (__e) {
    if (__isWasmFault(__e)) return __jsfb.prime_count(limit);
    throw __e;
  }
}
prime_count.__pyparams__ = ["limit"];
