// @generated by PythScribe — do not edit; regenerate with `pyths compile`.
export declare function fibonacci(n: number): number;
export declare function prime_count(limit: number): number;
export declare function format_result(label: any, value: any): any;
export declare function Greeting(): JSX.Element;
