// @generated by PythScribe — do not edit; regenerate with `pyths compile`.
import { pyStr } from "pyths-runtime";

import { createElement } from "react";
import { component } from "pyths-runtime/react";
export function format_result(label, value) {
    return `${pyStr(label)} = ${pyStr(value)}`;
}
format_result.__pyparams__ = ["label", "value"];
export function Greeting() {
    return createElement("div", null, createElement("h1", null, format_result("fib(20)", fibonacci(20))), createElement("p", null, format_result("primes < 100", prime_count(100))));
}

import { fibonacci, prime_count } from "./auto_route_demo.glue.js";
export { fibonacci, prime_count };
