// Auto-generated by PythScribe compiler — do not edit.
const __wasm = await (async () => {
  const imports = {};
  const url = new URL('./wasm_numeric.wasm', import.meta.url);
  if (typeof WebAssembly.instantiateStreaming === 'function') {
    return (await WebAssembly.instantiateStreaming(fetch(url), imports)).instance.exports;
  }
  const bytes = await fetch(url).then(r => r.arrayBuffer());
  return (await WebAssembly.instantiate(bytes, imports)).instance.exports;
})();

export function add(a, b) {
  return Number(__wasm.add(BigInt(Math.trunc(a)), BigInt(Math.trunc(b))));
}

export function factorial(n) {
  return Number(__wasm.factorial(BigInt(Math.trunc(n))));
}

export function multiply(x, y) {
  return __wasm.multiply(x, y);
}
