// Auto-generated by PythScribe compiler — do not edit.
const __wasm = await (async () => {
  const imports = {};
  const url = new URL('./wasm_bridge_mixed.wasm', import.meta.url);
  if (typeof WebAssembly.instantiateStreaming === 'function') {
    return (await WebAssembly.instantiateStreaming(fetch(url), imports)).instance.exports;
  }
  const bytes = await fetch(url).then(r => r.arrayBuffer());
  return (await WebAssembly.instantiate(bytes, imports)).instance.exports;
})();

export function add(a, b) {
  return Number(__wasm.add(BigInt(Math.trunc(a)), BigInt(Math.trunc(b))));
}

export function square(x) {
  return __wasm.square(x);
}
