// @generated by PythScribe — do not edit; regenerate with `pyths compile`.
// Auto-generated by PythScribe compiler — do not edit.
import { __pyF, __pyRangeIter, pyAdd, pyEq, pyGetItem, pyGt, pyMod, pyMul, pySub } from "./pyths-runtime/index.js";
const __PYTHS_ABI = { abi: 1, list_layout: "pyths-0.2.4-list-v1", array_layout: "pyths-0.2.5-array-v2" };
function __checkPythsAbi(module) {
  const secs = WebAssembly.Module.customSections(module, "pyths.abi");
  if (secs.length !== 1) throw new Error('pythscribe: WASM ABI check failed: expected exactly one `pyths.abi` custom section, found ' + secs.length + ' (this .wasm was not emitted by the pyths compiler that emitted this glue; rebuild the artifact)');
  let got;
  try { got = JSON.parse(new TextDecoder().decode(new Uint8Array(secs[0]))); } catch (e) { throw new Error('pythscribe: WASM ABI check failed: `pyths.abi` section is not valid JSON (' + e.message + ')'); }
  for (const f of ['abi', 'list_layout', 'array_layout']) {
    if (got[f] !== __PYTHS_ABI[f]) throw new Error('pythscribe: WASM ABI mismatch on `' + f + '`: module=' + JSON.stringify(got[f]) + ' glue=' + JSON.stringify(__PYTHS_ABI[f]) + ' -- rebuild the artifact with the matching pyths compiler (a mismatched layout would be read at the wrong width; refused, never silently)');
  }
}
const __wasm = await (async () => {
  const imports = {};
  const url = new URL('./luhn_ok.wasm', import.meta.url);
  const isNode = typeof globalThis.process !== 'undefined'
    && globalThis.process.versions != null
    && typeof globalThis.process.versions.node === 'string';
  let __module;
  if (isNode) {
    const { readFile } = await import('node:fs/promises');
    const { fileURLToPath } = await import('node:url');
    const bytes = await readFile(fileURLToPath(url));
    __module = await WebAssembly.compile(bytes);
  } else if (typeof WebAssembly.compileStreaming === 'function') {
    __module = await WebAssembly.compileStreaming(fetch(url));
  } else {
    const bytes = await fetch(url).then(r => r.arrayBuffer());
    __module = await WebAssembly.compile(bytes);
  }
  __checkPythsAbi(__module);
  const __instance = await WebAssembly.instantiate(__module, imports);
  return __instance.exports;
})();

const __encoder = new TextEncoder();
const __decoder = new TextDecoder();

function __str_to_wasm(s) {
  const bytes = __encoder.encode(s);
  const ptr = __wasm.__alloc(bytes.length + 4);
  const view = new DataView(__wasm.memory.buffer);
  view.setInt32(ptr, bytes.length, true);
  new Uint8Array(__wasm.memory.buffer).set(bytes, ptr + 4);
  return ptr;
}

function __str_from_wasm(ptr) {
  const view = new DataView(__wasm.memory.buffer);
  const len = view.getInt32(ptr, true);
  return __decoder.decode(new Uint8Array(__wasm.memory.buffer, ptr + 4, len));
}

function __list_to_wasm(arr, kind) {
  const n = arr.length;
  const esize = kind === 'i32' ? 4 : 8;
  const ptr = __wasm.__alloc(8 + n * esize);
  const view = new DataView(__wasm.memory.buffer);
  view.setInt32(ptr, n, true);
  view.setInt32(ptr + 4, n, true);
  for (let i = 0; i < n; i++) {
    const off = ptr + 8 + i * esize;
    if (kind === 'f64') view.setFloat64(off, arr[i], true);
    else if (kind === 'i64') {
      const b = typeof arr[i] === 'bigint' ? arr[i] : BigInt(Math.trunc(arr[i]));
      if (b > 9223372036854775807n || b < -9223372036854775808n) throw new RangeError('OverflowError: list element exceeds the i64 range of the WASM fast path');
      view.setBigInt64(off, b, true);
    }
    else view.setInt32(off, arr[i] | 0, true);
  }
  return ptr;
}

function __list_from_wasm(ptr, kind) {
  const view = new DataView(__wasm.memory.buffer);
  const n = view.getInt32(ptr, true);
  const esize = kind === 'i32' ? 4 : 8;
  const out = new Array(n);
  for (let i = 0; i < n; i++) {
    const off = ptr + 8 + i * esize;
    if (kind === 'f64') out[i] = view.getFloat64(off, true);
    else if (kind === 'i64') { const v = view.getBigInt64(off, true); out[i] = (v >= -9007199254740991n && v <= 9007199254740991n) ? Number(v) : v; }
    else out[i] = view.getInt32(off, true);
  }
  return out;
}

function __list_write_back(arr, ptr, kind) {
  const view = new DataView(__wasm.memory.buffer);
  const n = view.getInt32(ptr, true);
  if (n !== arr.length) throw new Error('PythScribe: @wasm out-parameter list length changed (' + arr.length + ' -> ' + n + '); a fixed-capacity linear-memory buffer cannot reflect a length-changing mutation — compile with --target js for that kernel');
  const esize = kind === 'i32' ? 4 : 8;
  const typed = ArrayBuffer.isView(arr);
  for (let i = 0; i < n; i++) {
    const off = ptr + 8 + i * esize;
    if (kind === 'f64') arr[i] = view.getFloat64(off, true);
    else if (kind === 'i64') { const v = view.getBigInt64(off, true); arr[i] = typed ? v : ((v >= -9007199254740991n && v <= 9007199254740991n) ? Number(v) : v); }
    else { const v = view.getInt32(off, true); arr[i] = typed ? v : (v !== 0); }
  }
}
const __i64ToJs = (v) => (v >= -9007199254740991n && v <= 9007199254740991n ? Number(v) : v);
class __PyFloatW extends Number { get __pyfloat__() { return true; } }
const __f64Box = (v) => (Number.isInteger(v) ? new __PyFloatW(v) : v);
const __i64Oob = (v) => typeof v === "bigint" && (v > 9223372036854775807n || v < -9223372036854775808n);

// #358: exact JS twins of the WASM-compiled functions. When a call
// would exceed i64 (the `__ovf` flag, or an out-of-range argument),
// the wrapper transparently re-runs it on these arbitrary-precision
// implementations — the WASM fast path never returns a wrapped value.
const __jsfb = (() => {

function luhn_ok(digits) {
    let d;
    let total = 0;
    let parity = pyMod(digits.length, 2);
    {
        const __r_start_0 = 0;
        const __r_stop_0 = digits.length;
        for (const __ri_0 of __pyRangeIter(__r_start_0, __r_stop_0, 1)) {
            let i = __ri_0;
            d = pyGetItem(digits, i);
            if (pyEq(pyMod(i, 2), parity)) {
                d = pyMul(d, 2);
                if (pyGt(d, 9)) {
                    d = pySub(d, 9);
                }
            }
            total = pyAdd(total, d);
        }
    }
    if (pyEq(pyMod(total, 10), 0)) {
        return __pyF(0);
    }
    return __pyF(1);
}
luhn_ok.__pyparams__ = ["digits"];
return { luhn_ok };
})();
const __isWasmFault = (e) => (typeof WebAssembly !== "undefined" && e instanceof WebAssembly.RuntimeError) || e instanceof RangeError;

export function luhn_ok(digits) {
  try {
  const __sp = __wasm.__heap_ptr.value;
  try {
    const __wb_arg_0 = __list_to_wasm(digits, "i64");
    const __raw = __wasm.luhn_ok(__wb_arg_0);
    if (__wasm.__ovf.value) {
      __wasm.__ovf.value = 0;
      return __jsfb.luhn_ok(digits);
    }
    __list_write_back(digits, __wb_arg_0, "i64");
    return __f64Box(__raw);
  } finally {
    __wasm.__heap_ptr.value = __sp;
  }
  } catch (__e) {
    if (__isWasmFault(__e)) return __jsfb.luhn_ok(digits);
    throw __e;
  }
}
luhn_ok.__pyparams__ = ["digits"];
