// @generated by PythScribe — do not edit; regenerate with `pyths compile`.
// Auto-generated by PythScribe compiler — do not edit.
import { __pyRangeIter, pyAdd, pyGetItem, pyGt, pyMul, pySetItem } from "./pyths-runtime/index.js";
const __PYTHS_ABI = { abi: 1, list_layout: "pyths-0.2.4-list-v1", array_layout: "pyths-0.2.5-array-v2" };
function __checkPythsAbi(module) {
  const secs = WebAssembly.Module.customSections(module, "pyths.abi");
  if (secs.length !== 1) throw new Error('pythscribe: WASM ABI check failed: expected exactly one `pyths.abi` custom section, found ' + secs.length + ' (this .wasm was not emitted by the pyths compiler that emitted this glue; rebuild the artifact)');
  let got;
  try { got = JSON.parse(new TextDecoder().decode(new Uint8Array(secs[0]))); } catch (e) { throw new Error('pythscribe: WASM ABI check failed: `pyths.abi` section is not valid JSON (' + e.message + ')'); }
  for (const f of ['abi', 'list_layout', 'array_layout']) {
    if (got[f] !== __PYTHS_ABI[f]) throw new Error('pythscribe: WASM ABI mismatch on `' + f + '`: module=' + JSON.stringify(got[f]) + ' glue=' + JSON.stringify(__PYTHS_ABI[f]) + ' -- rebuild the artifact with the matching pyths compiler (a mismatched layout would be read at the wrong width; refused, never silently)');
  }
}
const __wasm = await (async () => {
  const imports = {};
  const url = new URL('./threshold_lum.wasm', import.meta.url);
  const isNode = typeof globalThis.process !== 'undefined'
    && globalThis.process.versions != null
    && typeof globalThis.process.versions.node === 'string';
  let __module;
  if (isNode) {
    const { readFile } = await import('node:fs/promises');
    const { fileURLToPath } = await import('node:url');
    const bytes = await readFile(fileURLToPath(url));
    __module = await WebAssembly.compile(bytes);
  } else if (typeof WebAssembly.compileStreaming === 'function') {
    __module = await WebAssembly.compileStreaming(fetch(url));
  } else {
    const bytes = await fetch(url).then(r => r.arrayBuffer());
    __module = await WebAssembly.compile(bytes);
  }
  __checkPythsAbi(__module);
  const __instance = await WebAssembly.instantiate(__module, imports);
  return __instance.exports;
})();

const __encoder = new TextEncoder();
const __decoder = new TextDecoder();

function __str_to_wasm(s) {
  const bytes = __encoder.encode(s);
  const ptr = __wasm.__alloc(bytes.length + 4);
  const view = new DataView(__wasm.memory.buffer);
  view.setInt32(ptr, bytes.length, true);
  new Uint8Array(__wasm.memory.buffer).set(bytes, ptr + 4);
  return ptr;
}

function __str_from_wasm(ptr) {
  const view = new DataView(__wasm.memory.buffer);
  const len = view.getInt32(ptr, true);
  return __decoder.decode(new Uint8Array(__wasm.memory.buffer, ptr + 4, len));
}

const __ARR_DTYPES = {
  int32:   { ctor: Int32Array,    esize: 4, tag: 0 },
  int64:   { ctor: BigInt64Array, esize: 8, tag: 1 },
  float32: { ctor: Float32Array,  esize: 4, tag: 2 },
  float64: { ctor: Float64Array,  esize: 8, tag: 3 },
  uint8:   { ctor: Uint8Array,    esize: 1, tag: 4 },
};

function __arrRowOk(row, d) {
  return ArrayBuffer.isView(row) && row.constructor === d.ctor && row.BYTES_PER_ELEMENT === d.esize;
}

function __array_to_wasm(arr, dtype, ndim) {
  const d = __ARR_DTYPES[dtype];
  let nrows, ncols, n;
  if (ndim === 1) {
    if (!__arrRowOk(arr, d)) {
      const got = (arr && arr.constructor && arr.constructor.name) ? arr.constructor.name : typeof arr;
      throw new RangeError('pythscribe: Array[' + dtype + '] expects a ' + d.ctor.name + ' buffer (dtype/width match); got ' + got + ' — refused (rerouted to the JS path, never read at the wrong width)');
    }
    nrows = arr.length; ncols = 0; n = arr.length;
  } else if (ndim === 2) {
    if (!Array.isArray(arr)) throw new RangeError('pythscribe: Array[' + dtype + ', 2] expects an array of ' + d.ctor.name + ' rows; got ' + (typeof arr) + ' — refused');
    nrows = arr.length;
    ncols = 0;
    for (let r = 0; r < nrows; r++) {
      if (!__arrRowOk(arr[r], d)) throw new RangeError('pythscribe: Array[' + dtype + ', 2] row ' + r + ' must be a ' + d.ctor.name + ' buffer (dtype/width match) — refused');
      if (r === 0) ncols = arr[0].length;
      if (arr[r].length !== ncols) throw new RangeError('pythscribe: Array[' + dtype + ', 2] is ragged (row ' + r + ' length ' + arr[r].length + ' != ' + ncols + '); only C-contiguous rectangular 2-D arrays cross — refused');
    }
    n = nrows * ncols;
  } else {
    throw new RangeError('pythscribe: Array marshalling supports ndim ∈ {1, 2}; got ndim=' + ndim + ' — refused');
  }
  const allocSize = ((16 + n * d.esize + 7) & ~7) + 8;
  const raw = __wasm.__alloc(allocSize);
  const ptr = (raw + 7) & ~7;
  const view = new DataView(__wasm.memory.buffer);
  view.setInt32(ptr, d.tag, true);
  view.setInt32(ptr + 4, ndim, true);
  view.setInt32(ptr + 8, nrows, true);
  view.setInt32(ptr + 12, ncols, true);
  if (ndim === 1) {
    new d.ctor(__wasm.memory.buffer, ptr + 16, n).set(arr);
  } else {
    for (let r = 0; r < nrows; r++) new d.ctor(__wasm.memory.buffer, ptr + 16 + r * ncols * d.esize, ncols).set(arr[r]);
  }
  return ptr;
}

function __array_write_back(arr, ptr, dtype, ndim) {
  const d = __ARR_DTYPES[dtype];
  const view = new DataView(__wasm.memory.buffer);
  const tag = view.getInt32(ptr, true);
  const hdrNdim = view.getInt32(ptr + 4, true);
  const nrows = view.getInt32(ptr + 8, true);
  const ncols = view.getInt32(ptr + 12, true);
  if (tag !== d.tag) throw new Error('PythScribe: @wasm array write-back dtype tag ' + tag + ' != expected ' + d.tag + ' (' + dtype + '); a wrong-width read would corrupt values — refused');
  if (hdrNdim !== ndim) throw new Error('PythScribe: @wasm array write-back ndim ' + hdrNdim + ' != expected ' + ndim + '; refused');
  if (ndim === 1) {
    if (nrows !== arr.length) throw new Error('PythScribe: @wasm array out-parameter length changed (' + arr.length + ' -> ' + nrows + '); a fixed-capacity linear-memory buffer cannot reflect a length-changing mutation — compile with --target js for that kernel');
    arr.set(new d.ctor(__wasm.memory.buffer, ptr + 16, nrows));
  } else {
    if (nrows !== arr.length) throw new Error('PythScribe: @wasm 2-D array out-parameter row count changed (' + arr.length + ' -> ' + nrows + '); refused');
    for (let r = 0; r < nrows; r++) {
      if (arr[r].length !== ncols) throw new Error('PythScribe: @wasm 2-D array out-parameter row ' + r + ' length changed (' + arr[r].length + ' -> ' + ncols + '); refused');
      arr[r].set(new d.ctor(__wasm.memory.buffer, ptr + 16 + r * ncols * d.esize, ncols));
    }
  }
}
const __i64ToJs = (v) => (v >= -9007199254740991n && v <= 9007199254740991n ? Number(v) : v);
const __i64Oob = (v) => typeof v === "bigint" && (v > 9223372036854775807n || v < -9223372036854775808n);

// #358: exact JS twins of the WASM-compiled functions. When a call
// would exceed i64 (the `__ovf` flag, or an out-of-range argument),
// the wrapper transparently re-runs it on these arbitrary-precision
// implementations — the WASM fast path never returns a wrapped value.
const __jsfb = (() => {

function threshold_lum(img, out, h, w, thr) {
    let x;
    let c;
    let s;
    let v;
    {
        const __r_start_0 = 0;
        const __r_stop_0 = h;
        for (const __ri_0 of __pyRangeIter(__r_start_0, __r_stop_0, 1)) {
            let y = __ri_0;
            {
                const __r_start_1 = 0;
                const __r_stop_1 = w;
                for (const __ri_1 of __pyRangeIter(__r_start_1, __r_stop_1, 1)) {
                    x = __ri_1;
                    c = pyMul(x, 3);
                    s = pyAdd(pyAdd(pyGetItem(pyGetItem(img, y), c), pyGetItem(pyGetItem(img, y), pyAdd(c, 1))), pyGetItem(pyGetItem(img, y), pyAdd(c, 2)));
                    v = 0;
                    if (pyGt(s, thr)) {
                        v = 255;
                    }
                    pySetItem(pyGetItem(out, y), c, v);
                    pySetItem(pyGetItem(out, y), pyAdd(c, 1), v);
                    pySetItem(pyGetItem(out, y), pyAdd(c, 2), v);
                }
            }
        }
    }
    return pyMul(h, w);
}
threshold_lum.__pyparams__ = ["img", "out", "h", "w", "thr"];
return { threshold_lum };
})();
const __isWasmFault = (e) => (typeof WebAssembly !== "undefined" && e instanceof WebAssembly.RuntimeError) || e instanceof RangeError;

export function threshold_lum(img, out, h, w, thr) {
  try {
  if (__i64Oob(h) || __i64Oob(w) || __i64Oob(thr)) return __jsfb.threshold_lum(img, out, h, w, thr);
  const __sp = __wasm.__heap_ptr.value;
  try {
    const __wb_arg_0 = __array_to_wasm(img, "uint8", 2);
    const __wb_arg_1 = __array_to_wasm(out, "uint8", 2);
    const __raw = __wasm.threshold_lum(__wb_arg_0, __wb_arg_1, (typeof h === "bigint" ? h : BigInt(Math.trunc(h))), (typeof w === "bigint" ? w : BigInt(Math.trunc(w))), (typeof thr === "bigint" ? thr : BigInt(Math.trunc(thr))));
    if (__wasm.__ovf.value) {
      __wasm.__ovf.value = 0;
      return __jsfb.threshold_lum(img, out, h, w, thr);
    }
    __array_write_back(img, __wb_arg_0, "uint8", 2);
    __array_write_back(out, __wb_arg_1, "uint8", 2);
    return __i64ToJs(__raw);
  } finally {
    __wasm.__heap_ptr.value = __sp;
  }
  } catch (__e) {
    if (__isWasmFault(__e)) return __jsfb.threshold_lum(img, out, h, w, thr);
    throw __e;
  }
}
threshold_lum.__pyparams__ = ["img", "out", "h", "w", "thr"];
